<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="CotizacionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_ListarRel_TipoElementoAlmacen_FactorCotizacion" Method="stp_ListarRel_TipoElementoAlmacen_FactorCotizacion">
    <Parameter Name="intTipoElementoAlmacen_FactorID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intTipoElementoAlmacenID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintFactorID" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="stp_ListarRel_TipoElementoAlmacen_FactorCotizacionResult">
      <Column Name="intTipoElementoAlmacen_FactorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intTipoElementoAlmacenID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintFactorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchFactor" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="decFactor" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="datFechaAlta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarCotizacion" Method="stp_ListarCotizacion">
    <Parameter Name="intEmpresaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarCotizacionResult">
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intEstatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintPrioridadID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intEmpresaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchNombre" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="vchFolio" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="datFechaCotizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datFechaAceptacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datFechaRechazo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="intRelCotizaProductoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intProductoGralID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datFechaArmado" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="intSubProductoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDetCotizacion" Method="stp_setDetCotizacion">
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intSeleccionVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intPartida" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="decDolar" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decMonto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decSubtotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decDescuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decDescuentoFin" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decIEMPS" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decRetISR" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decRetIVA" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decIVA" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDetCotizacionResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(58) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosPantallaCotizacion" Method="stp_ListarDatosPantallaCotizacion">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosPantallaCotizacionResult">
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intEmpresaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intEstatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintPrioridadID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="datFechaAceptacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datFechaCotizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datFechaRechazo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="vchFolio" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intRackID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bitMontacarga" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="intRelCotizaProductoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intProductoGralID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intSubProductoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchDimensionMontacarga" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="intNumeroNivelSobreViga" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intPosicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintVisitas" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosCotizacion" Method="stp_ListarDatosCotizacion">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intEstatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPrioridadID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intEmpresaID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosCotizacionResult">
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intRackID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchNombreCliente" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intEmpresaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchFolio" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="vchEstatus" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="vchPrioridad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="datFechaCotizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datFechaAceptacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datFechaRechazo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="intProductoGralID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intSubProductoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decMonto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="decIVA" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="decTotal" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setMstCotizacion" Method="stp_setMstCotizacion">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intEstatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPrioridadID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intEmpresaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="vchFolio" Type="System.String" DbType="VarChar(250)" />
    <Parameter Name="datFechaAceptacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="datFechaRechazo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="intRack" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintVisitas" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intRelCotizaProductoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intProductoGralID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intSubProductoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setMstCotizacionResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(263)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDetalleCotizacion" Method="stp_ListarDetalleCotizacion">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDetalleCotizacionResult">
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intRackID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intSeleccionVigaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intSeleccionMarcoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintMontajeID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intPartida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decMedidaFrente" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decMedidaFondo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAlto" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decPesoKg" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="bitMontacarga" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="intNumeroTarimaPorNivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intPosicion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintVisitas" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="decDolar" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decMonto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decSubtotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decDescuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decDescuentoFin" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decIEMPS" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decRetISR" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decRetIVA" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decIVA" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosSistemaSelectivo" Method="stp_ListarDatosSistemaSelectivo">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosSistemaSelectivoResult">
      <Column Name="intTipoElementoCoti_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDatosVigaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDatoMarcoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDatosPanelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDatosCrossBarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDistanciadorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intTipoElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intTipoElementoAlmacenID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intParrillaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intVigaTopeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intProtectorPosteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intProtectorBateriaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintSistemaCargaMarcoID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intDatoTornilleriaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosRelSistemaSelectivo" Method="stp_setDatosRelSistemaSelectivo">
    <Parameter Name="intTipoElementoCoti_ProductoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intTipoElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intTipoElementoAlmacenID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatoMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatosVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatosPanelID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatosCrossBarID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDistanciadorID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intParrillaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intVigaTopeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intProtectorPosteID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intProtectorBateriaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintSistemaCargaMarcoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="datFechaAlta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosRelSistemaSelectivoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(52) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>