#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adsisplus.Cotyrsa.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbTyrsa")]
	public partial class CrossBarDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public CrossBarDataContext() : 
				base(global::Adsisplus.Cotyrsa.DataAccess.Properties.Settings.Default.dbTyrsaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CrossBarDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrossBarDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrossBarDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrossBarDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarDatosCrossBar")]
		public ISingleResult<stp_ListarDatosCrossBarResult> stp_ListarDatosCrossBar([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatosCrossBarID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intElementoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatoMarcoID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intDatosCrossBarID, intElementoID, intDatoMarcoID);
			return ((ISingleResult<stp_ListarDatosCrossBarResult>)(result.ReturnValue));
		}
	}
	
	public partial class stp_ListarDatosCrossBarResult
	{
		
		private int _intDatosCrossBarID;
		
		private string _vchElemento;
		
		private System.Nullable<short> _sintCantidadDatoMarco;
		
		private System.Nullable<decimal> _decAnchoCrossBar;
		
		private System.Nullable<bool> _bitConectorVigaCrossbar;
		
		private System.Nullable<int> _intCantidadNivelCrossbar;
		
		private System.Nullable<bool> _bitActivo;
		
		public stp_ListarDatosCrossBarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDatosCrossBarID", DbType="Int NOT NULL")]
		public int intDatosCrossBarID
		{
			get
			{
				return this._intDatosCrossBarID;
			}
			set
			{
				if ((this._intDatosCrossBarID != value))
				{
					this._intDatosCrossBarID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchElemento", DbType="VarChar(25)")]
		public string vchElemento
		{
			get
			{
				return this._vchElemento;
			}
			set
			{
				if ((this._vchElemento != value))
				{
					this._vchElemento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintCantidadDatoMarco", DbType="SmallInt")]
		public System.Nullable<short> sintCantidadDatoMarco
		{
			get
			{
				return this._sintCantidadDatoMarco;
			}
			set
			{
				if ((this._sintCantidadDatoMarco != value))
				{
					this._sintCantidadDatoMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAnchoCrossBar", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> decAnchoCrossBar
		{
			get
			{
				return this._decAnchoCrossBar;
			}
			set
			{
				if ((this._decAnchoCrossBar != value))
				{
					this._decAnchoCrossBar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitConectorVigaCrossbar", DbType="Bit")]
		public System.Nullable<bool> bitConectorVigaCrossbar
		{
			get
			{
				return this._bitConectorVigaCrossbar;
			}
			set
			{
				if ((this._bitConectorVigaCrossbar != value))
				{
					this._bitConectorVigaCrossbar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadNivelCrossbar", DbType="Int")]
		public System.Nullable<int> intCantidadNivelCrossbar
		{
			get
			{
				return this._intCantidadNivelCrossbar;
			}
			set
			{
				if ((this._intCantidadNivelCrossbar != value))
				{
					this._intCantidadNivelCrossbar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
