#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adsisplus.Cotyrsa.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbTyrsa")]
	public partial class DireccionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DireccionDataContext() : 
				base(global::Adsisplus.Cotyrsa.DataAccess.Properties.Settings.Default.dbTyrsaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DireccionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DireccionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DireccionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DireccionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarDireccion")]
		public ISingleResult<stp_ListarDireccionResult> stp_ListarDireccion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDireccionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intMunicipioID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intEstadoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intLocalidadID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoDomicilioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intDireccionID, intMunicipioID, intEstadoID, intLocalidadID, intTipoDomicilioID);
			return ((ISingleResult<stp_ListarDireccionResult>)(result.ReturnValue));
		}
	}
	
	public partial class stp_ListarDireccionResult
	{
		
		private int _intDireccionID;
		
		private string _vchMunicipio;
		
		private string _vchEstado;
		
		private string _vchLocalidad;
		
		private string _vchTipoDomicilio;
		
		private string _vchCalle;
		
		private string _vchNumExterior;
		
		private string _vchNumInterior;
		
		private string _vchColonia;
		
		private string _vchCP;
		
		private System.Nullable<bool> _bitActivo;
		
		public stp_ListarDireccionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDireccionID", DbType="Int NOT NULL")]
		public int intDireccionID
		{
			get
			{
				return this._intDireccionID;
			}
			set
			{
				if ((this._intDireccionID != value))
				{
					this._intDireccionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMunicipio", DbType="VarChar(120)")]
		public string vchMunicipio
		{
			get
			{
				return this._vchMunicipio;
			}
			set
			{
				if ((this._vchMunicipio != value))
				{
					this._vchMunicipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchEstado", DbType="VarChar(80)")]
		public string vchEstado
		{
			get
			{
				return this._vchEstado;
			}
			set
			{
				if ((this._vchEstado != value))
				{
					this._vchEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchLocalidad", DbType="VarChar(120)")]
		public string vchLocalidad
		{
			get
			{
				return this._vchLocalidad;
			}
			set
			{
				if ((this._vchLocalidad != value))
				{
					this._vchLocalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipoDomicilio", DbType="VarChar(25)")]
		public string vchTipoDomicilio
		{
			get
			{
				return this._vchTipoDomicilio;
			}
			set
			{
				if ((this._vchTipoDomicilio != value))
				{
					this._vchTipoDomicilio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCalle", DbType="VarChar(100)")]
		public string vchCalle
		{
			get
			{
				return this._vchCalle;
			}
			set
			{
				if ((this._vchCalle != value))
				{
					this._vchCalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNumExterior", DbType="VarChar(10)")]
		public string vchNumExterior
		{
			get
			{
				return this._vchNumExterior;
			}
			set
			{
				if ((this._vchNumExterior != value))
				{
					this._vchNumExterior = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNumInterior", DbType="VarChar(10)")]
		public string vchNumInterior
		{
			get
			{
				return this._vchNumInterior;
			}
			set
			{
				if ((this._vchNumInterior != value))
				{
					this._vchNumInterior = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchColonia", DbType="VarChar(100)")]
		public string vchColonia
		{
			get
			{
				return this._vchColonia;
			}
			set
			{
				if ((this._vchColonia != value))
				{
					this._vchColonia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCP", DbType="VarChar(5)")]
		public string vchCP
		{
			get
			{
				return this._vchCP;
			}
			set
			{
				if ((this._vchCP != value))
				{
					this._vchCP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
