<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="DistanciadorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_ListarSeleccionDistanciador" Method="stp_ListarSeleccionDistanciador">
    <Parameter Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" />
    <ElementType Name="stp_ListarSeleccionDistanciadorResult">
      <Column Name="vchSKU" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="decAltura" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decPesoKg" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="decPrecioTyrsa" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="decPrecioReferencia" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="decRelacionPrecio" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="decPrecioMetroTyrsa" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="decPrecioMetroRef" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="decPrecioKgTyrsa" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="decPrecioKgRef" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="decPesoAnguloCobro" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="decPesoPlacaCobro" Type="System.Decimal" DbType="Decimal(10,4)" CanBeNull="true" />
      <Column Name="sintCantidadPzaAngulo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sintCantidadPzaPlaca" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="decPesoPorDistanciador" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="decAreaPinturaAngulo" Type="System.Decimal" DbType="Decimal(10,4)" CanBeNull="true" />
      <Column Name="decAreaPinturaPlaca" Type="System.Decimal" DbType="Decimal(10,4)" CanBeNull="true" />
      <Column Name="decPinturaTotal" Type="System.Decimal" DbType="Decimal(10,4)" CanBeNull="true" />
      <Column Name="decTotalKgTotal" Type="System.Decimal" DbType="Decimal(10,4)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosDistanciador" Method="stp_ListarDatosDistanciador">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosDistanciadorResult">
      <Column Name="intDistanciadorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchFolio" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchPintura" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intCantidadDistanciador" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decLargoDistanciador" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarCatAlturaDistanciador" Method="stp_ListarCatAlturaDistanciador">
    <ElementType Name="stp_ListarCatAlturaDistanciadorResult">
      <Column Name="decAltura" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>