<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="EstanteriaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_ListarEntrepanio" Method="stp_ListarEntrepanio">
    <Parameter Name="sintRefuerzo" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decFrente" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decFondo" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="intCalibreAceroID" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitGalvanizado" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="stp_ListarEntrepanioResult">
      <Column Name="vchCalibreAcero" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="decFondo" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decFrente" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="sintNumRefuerzo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intCapCargaXEntrepanio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decDesarrollo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decLongitud" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="vchMaterial" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="decTotalKiloUnitario" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="decPrecioFinal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>