#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adsisplus.Cotyrsa.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbTyrsa")]
	public partial class GastosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public GastosDataContext() : 
				base(global::Adsisplus.Cotyrsa.DataAccess.Properties.Settings.Default.dbTyrsaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GastosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GastosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GastosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GastosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarDatosPantallaGasto")]
		public ISingleResult<stp_ListarDatosPantallaGastoResult> stp_ListarDatosPantallaGasto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDetCotizaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCotizacionID, intDetCotizaID);
			return ((ISingleResult<stp_ListarDatosPantallaGastoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_setDatosFlete")]
		public ISingleResult<stp_setDatosFleteResult> stp_setDatosFlete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDetCotizaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatoFleteID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intElementoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sintFleteID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> datFechaCarga, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> datFechaDescarga, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitActivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> tinOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCotizacionID, intDetCotizaID, intDatoFleteID, intElementoID, sintFleteID, intCantidad, datFechaCarga, datFechaDescarga, bitActivo, tinOpcion);
			return ((ISingleResult<stp_setDatosFleteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_setDatosInstalacion")]
		public ISingleResult<stp_setDatosInstalacionResult> stp_setDatosInstalacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDetCotizaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatosInstalacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintInstalacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intElementoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> datFecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitActivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> tinOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCotizacionID, intDetCotizaID, intDatosInstalacionID, sintInstalacionID, intElementoID, intCantidad, datFecha, bitActivo, tinOpcion);
			return ((ISingleResult<stp_setDatosInstalacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_setDatosViatico")]
		public ISingleResult<stp_setDatosViaticoResult> stp_setDatosViatico([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDetCotizaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatoViaticoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intElementoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintViaticoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> datFecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitActivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> tinOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCotizacionID, intDetCotizaID, intDatoViaticoID, intElementoID, sintViaticoID, intCantidad, datFecha, bitActivo, tinOpcion);
			return ((ISingleResult<stp_setDatosViaticoResult>)(result.ReturnValue));
		}
	}
	
	public partial class stp_ListarDatosPantallaGastoResult
	{
		
		private int _intCotizacionID;
		
		private int _intDetCotizaID;
		
		private int _intDatoFleteID;
		
		private System.Nullable<short> _sintFleteID;
		
		private System.Nullable<int> _intCantidadFlete;
		
		private System.Nullable<System.DateTime> _datFechaCarga;
		
		private System.Nullable<System.DateTime> _datFechaDescarga;
		
		private int _intDatosInstalacionID;
		
		private System.Nullable<short> _sintInstalacionID;
		
		private System.Nullable<int> _intCantidadInstalacion;
		
		private System.Nullable<System.DateTime> _datFechaInstalacion;
		
		private int _intDatoViaticoID;
		
		private System.Nullable<short> _sintViaticoID;
		
		private System.Nullable<int> _intCantidadViaticos;
		
		private System.Nullable<System.DateTime> _datFechaViatico;
		
		public stp_ListarDatosPantallaGastoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCotizacionID", DbType="Int NOT NULL")]
		public int intCotizacionID
		{
			get
			{
				return this._intCotizacionID;
			}
			set
			{
				if ((this._intCotizacionID != value))
				{
					this._intCotizacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDetCotizaID", DbType="Int NOT NULL")]
		public int intDetCotizaID
		{
			get
			{
				return this._intDetCotizaID;
			}
			set
			{
				if ((this._intDetCotizaID != value))
				{
					this._intDetCotizaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDatoFleteID", DbType="Int NOT NULL")]
		public int intDatoFleteID
		{
			get
			{
				return this._intDatoFleteID;
			}
			set
			{
				if ((this._intDatoFleteID != value))
				{
					this._intDatoFleteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintFleteID", DbType="SmallInt")]
		public System.Nullable<short> sintFleteID
		{
			get
			{
				return this._sintFleteID;
			}
			set
			{
				if ((this._sintFleteID != value))
				{
					this._sintFleteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadFlete", DbType="Int")]
		public System.Nullable<int> intCantidadFlete
		{
			get
			{
				return this._intCantidadFlete;
			}
			set
			{
				if ((this._intCantidadFlete != value))
				{
					this._intCantidadFlete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFechaCarga", DbType="Date")]
		public System.Nullable<System.DateTime> datFechaCarga
		{
			get
			{
				return this._datFechaCarga;
			}
			set
			{
				if ((this._datFechaCarga != value))
				{
					this._datFechaCarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFechaDescarga", DbType="Date")]
		public System.Nullable<System.DateTime> datFechaDescarga
		{
			get
			{
				return this._datFechaDescarga;
			}
			set
			{
				if ((this._datFechaDescarga != value))
				{
					this._datFechaDescarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDatosInstalacionID", DbType="Int NOT NULL")]
		public int intDatosInstalacionID
		{
			get
			{
				return this._intDatosInstalacionID;
			}
			set
			{
				if ((this._intDatosInstalacionID != value))
				{
					this._intDatosInstalacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintInstalacionID", DbType="SmallInt")]
		public System.Nullable<short> sintInstalacionID
		{
			get
			{
				return this._sintInstalacionID;
			}
			set
			{
				if ((this._sintInstalacionID != value))
				{
					this._sintInstalacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadInstalacion", DbType="Int")]
		public System.Nullable<int> intCantidadInstalacion
		{
			get
			{
				return this._intCantidadInstalacion;
			}
			set
			{
				if ((this._intCantidadInstalacion != value))
				{
					this._intCantidadInstalacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFechaInstalacion", DbType="Date")]
		public System.Nullable<System.DateTime> datFechaInstalacion
		{
			get
			{
				return this._datFechaInstalacion;
			}
			set
			{
				if ((this._datFechaInstalacion != value))
				{
					this._datFechaInstalacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDatoViaticoID", DbType="Int NOT NULL")]
		public int intDatoViaticoID
		{
			get
			{
				return this._intDatoViaticoID;
			}
			set
			{
				if ((this._intDatoViaticoID != value))
				{
					this._intDatoViaticoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintViaticoID", DbType="SmallInt")]
		public System.Nullable<short> sintViaticoID
		{
			get
			{
				return this._sintViaticoID;
			}
			set
			{
				if ((this._sintViaticoID != value))
				{
					this._sintViaticoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadViaticos", DbType="Int")]
		public System.Nullable<int> intCantidadViaticos
		{
			get
			{
				return this._intCantidadViaticos;
			}
			set
			{
				if ((this._intCantidadViaticos != value))
				{
					this._intCantidadViaticos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFechaViatico", DbType="Date")]
		public System.Nullable<System.DateTime> datFechaViatico
		{
			get
			{
				return this._datFechaViatico;
			}
			set
			{
				if ((this._datFechaViatico != value))
				{
					this._datFechaViatico = value;
				}
			}
		}
	}
	
	public partial class stp_setDatosFleteResult
	{
		
		private string _vchResultado;
		
		private string _vchDescripcion;
		
		public stp_setDatosFleteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchResultado", DbType="VarChar(30)")]
		public string vchResultado
		{
			get
			{
				return this._vchResultado;
			}
			set
			{
				if ((this._vchResultado != value))
				{
					this._vchResultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
	
	public partial class stp_setDatosInstalacionResult
	{
		
		private string _vchResultado;
		
		private string _vchDescripcion;
		
		public stp_setDatosInstalacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchResultado", DbType="VarChar(30)")]
		public string vchResultado
		{
			get
			{
				return this._vchResultado;
			}
			set
			{
				if ((this._vchResultado != value))
				{
					this._vchResultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
	
	public partial class stp_setDatosViaticoResult
	{
		
		private string _vchResultado;
		
		private string _vchDescripcion;
		
		public stp_setDatosViaticoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchResultado", DbType="VarChar(30)")]
		public string vchResultado
		{
			get
			{
				return this._vchResultado;
			}
			set
			{
				if ((this._vchResultado != value))
				{
					this._vchResultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
