<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="GuiaEntradaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_ListarGuiaMontacargaDiveIn" Method="stp_ListarGuiaMontacargaDiveIn">
    <Parameter Name="sintLargoID" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="stp_ListarGuiaMontacargaDiveInResult">
      <Column Name="sintDriveInID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="decTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decTotalKiloUnitario" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="vchMedida" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="decPrecioFinal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPrecioMasLargoTotal" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosGuiaEntrada" Method="stp_ListarDatosGuiaEntrada">
    <Parameter Name="intGuiaEntradaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosGuiaEntradaResult">
      <Column Name="intGuiaEntradaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="decLargo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="intCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPrecioTotal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="intSeleccionGuiaMontaCargaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="decTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decTotalKiloUnitario" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="vchMedida" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="decPrecioFinal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPrecioMasLargoTotal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarSeleccionGuiaMontaCarga" Method="stp_ListarSeleccionGuiaMontaCarga">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarSeleccionGuiaMontaCargaResult">
      <Column Name="intSeleccionGuiaMontaCargaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intGuiaEntradaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decTotalKiloUnitario" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="vchMedida" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="decPrecioFinal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPrecioMasLargoTotal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>