<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="MarcosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="" Member="FactorMarcoSP">
    <Type Name="FactorMarcoSP" Id="ID1">
      <Column Name="sintFactorMarcoID" Type="System.Int16" CanBeNull="false" />
      <Column Name="vchDescCorta" Type="System.String" CanBeNull="false" />
      <Column Name="vchContanteMarco" Type="System.String" CanBeNull="false" />
      <Column Name="decCosto" Type="System.Decimal" CanBeNull="false" />
      <Column Name="datFechaAlta" Type="System.DateTime" CanBeNull="false" />
      <Column Name="bitActivo" Type="System.Boolean" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="CargaMarcoSP">
    <Type Name="CargaMarcoSP" Id="ID2">
      <Column Name="bitActivo" Type="System.Boolean" CanBeNull="false" />
      <Column Name="decAlturaPandeoM" Type="System.Decimal" CanBeNull="false" />
      <Column Name="intAlturaPandeoIN" Type="System.Int32" CanBeNull="false" />
      <Column Name="intCapacidadPeso" Type="System.Int32" CanBeNull="false" />
      <Column Name="intCargaMarcoID" Type="System.Int32" CanBeNull="false" />
      <Column Name="vchCalibreAcero" Type="System.String" CanBeNull="false" />
      <Column Name="vchFondoMercadoA" Type="System.String" CanBeNull="false" />
      <Column Name="vchFondoMercadoB" Type="System.String" CanBeNull="false" />
      <Column Name="vchFondoTyrsa" Type="System.String" CanBeNull="false" />
      <Column Name="vchFrenteMercadoA" Type="System.String" CanBeNull="false" />
      <Column Name="vchFrenteMercadoB" Type="System.String" CanBeNull="false" />
      <Column Name="vchFrenteTyrsa" Type="System.String" CanBeNull="false" />
      <Column Name="vchTipoMarcoTyrsa" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="CargaPosteSP">
    <Type Name="CargaPosteSP" Id="ID3">
      <Column Name="bitActivo" Type="System.Boolean" CanBeNull="false" />
      <Column Name="intCargaPosteID" Type="System.Int32" CanBeNull="false" />
      <Column Name="sintTipoMarcoID" Type="System.Int16" CanBeNull="false" />
      <Column Name="vchTipoMarcoTyrsa" Type="System.String" CanBeNull="false" />
      <Column Name="intCalibreAceroID" Type="System.Int32" CanBeNull="false" />
      <Column Name="vchCalibreAcero" Type="System.String" CanBeNull="false" />
      <Column Name="vchFrenteTyrsa" Type="System.String" CanBeNull="false" />
      <Column Name="vchFrenteMercadoA" Type="System.String" CanBeNull="false" />
      <Column Name="vchFrenteMercadoB" Type="System.String" CanBeNull="false" />
      <Column Name="vchFondoTyrsa" Type="System.String" CanBeNull="false" />
      <Column Name="vchFondoMercadoA" Type="System.String" CanBeNull="false" />
      <Column Name="vchFondoMercadoB" Type="System.String" CanBeNull="false" />
      <Column Name="decAlturaPandeoM" Type="System.Decimal" CanBeNull="false" />
      <Column Name="intAlturaPandeoIN" Type="System.Int32" CanBeNull="false" />
      <Column Name="intCapacidadPeso" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="entSeleccionMarco">
    <Type Name="entSeleccionMarco" Id="ID4">
      <Column Name="SKU" Type="System.String" CanBeNull="false" />
      <Column Name="intConfiguraMarcoID" Type="System.Int32" CanBeNull="false" />
      <Column Name="decPesoMarco" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" CanBeNull="false" />
      <Column Name="vchTipo" Type="System.String" CanBeNull="false" />
      <Column Name="vchMaterial" Type="System.String" CanBeNull="false" />
      <Column Name="decFondo" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decAltura" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decAlturaPandeo" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decCapacidadMarco" Type="System.Decimal" CanBeNull="false" />
      <Column Name="intTipoID" Type="System.Int32" CanBeNull="false" />
      <Column Name="intMaterialID" Type="System.Int32" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.stp_RelSistemaCargaMarcoPoste" Method="stp_RelSistemaCargaMarcoPoste">
    <Parameter Name="sintSistemaCargaMarcoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intSubProductoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCargaPosteID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCargaMarcoID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_RelSistemaCargaMarcoPosteResult">
      <Column Name="sintSistemaCargaMarcoID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="vchDescripcionSub" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="vchFondoTyrsaPoste" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="vchFondoTyrsaMarco" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ActualizaFactorMarco" Method="stp_ActualizaFactorMarco">
    <Parameter Name="sintFondoMarcoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decCostoLamina" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decCostoSolera" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactorAcero" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_ActualizaFactorMarcoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="vchDescripcion" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarCatFactorMarco" Method="stp_ListarCatFactorMarco">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.stp_ListarCatCargaMarco" Method="stp_ListarCatCargaMarco">
    <Parameter Name="intCargaMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintTipoMarcoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCalibreAceroID" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.stp_ListarCatCargaPoste" Method="stp_ListarCatCargaPoste">
    <Parameter Name="intCargaPosteID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintTipoMarcoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCalibreAceroID" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.stp_ConfiguraMarco" Method="stp_ConfiguraMarco">
    <Parameter Name="intConfiguraMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintTipoMarcoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intAlturaMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintFondoMarcoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intSKUID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintFactorMarcoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decFondoMarco" Type="System.Decimal" DbType="Decimal(8,4)" />
    <ElementType Name="stp_ConfiguraMarcoResult">
      <Column Name="intConfiguraMarcoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="vchTipoMarcoTyrsa" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="sintSKU" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="decAlturaMarco" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decFondoMarco" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="vchContanteMarco" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="decCalibre" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decSolera" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decTotalKilo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decPrecioTyrsa" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decRelacionPrecios" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decPrecioTyrsaMetro" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decPrecioTyrsaKg" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="sintNumPosteReq" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sintNumTravesanio" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sintDiagonalLarga" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sintDiagonalCorta" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="decPesoCobroLam14" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="decPintaPoste" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="decPintaTravesanio" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="decPintaDiagonalLarga" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="decPintaDiagonalCorta" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="decPintaPlacaBase" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="decTotalMarcoCompleto" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="decCalibreDosCaras" Type="System.Decimal" DbType="Decimal(12,3)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setFondoMarco" Method="stp_setFondoMarco">
    <Parameter Name="sintFondoMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decFactor1" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor2" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor3" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor5" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor7" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor9" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor11" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor13" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor15" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor17" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="decFactor18" Type="System.Decimal" DbType="Decimal(18,4)" />
    <ElementType Name="stp_setFondoMarcoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarFondoMarco" Method="stp_ListarFondoMarco">
    <ElementType Name="stp_ListarFondoMarcoResult">
      <Column Name="decFondoMarco" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setSeleccionMarco" Method="stp_setSeleccionMarco">
    <Parameter Name="intRackID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intSeleccionMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intConfiguraMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SKU" Parameter="sKU" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="decPesoMarco" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="intTipoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intMaterialID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decFondo" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAlturaPandeo" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decCapacidadMarco" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decFondoMarco" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAlturaMarco" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="tinOpcionMarco" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="decDimensionClaro" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decNNSVS" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decMargenExcedente" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAlturaPiso" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decNNSV" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decNNPVS" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decCargaModulo" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAlturaPandeoRack" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setSeleccionMarcoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(57) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosMarco" Method="stp_ListarDatosMarco">
    <Parameter Name="intDatoMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="stp_ListarDatosMarcoResult">
      <Column Name="intDatoMarcoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchPintura" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intConfiguraMarcoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintCantidad" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="decMedidaFondo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decMedidaAlto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="bitDobleMonten" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="intNumeroNivelSobreViga" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decAlturaPandeo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decCapacidadxNivel" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="sintCantidad1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarSeleccionMarco" Method="stp_ListarSeleccionMarco">
    <Parameter Name="decCapacidadCarga" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAlturaPandeo" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decFondo" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAlturaMarco" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="Sistema" Parameter="sistema" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="bitEstructural" Type="System.Boolean" DbType="Bit" />
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.stp_ListarDatosSeleccionMarco" Method="stp_ListarDatosSeleccionMarco">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosSeleccionMarcoResult">
      <Column Name="intSeleccionMarcoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SKU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="decPesoMarco" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intTipoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchTipo" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intMaterialID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchMaterialID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="decFondo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAlturaPandeo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decCapacidadMarco" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosPantallaMarco" Method="stp_ListarDatosPantallaMarco">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intSeleccionMarcoID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosPantallaMarcoResult">
      <Column Name="intRackID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intSeleccionMarcoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sintCantidad" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="bitEstructural" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="decFondoMarco" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="tinOpcionMarco" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="decDimensionClaro" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decNNSVS" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decMargenExcedente" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAlturaMarco" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAlturaPiso" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decNNSV" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decNNPVS" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decCargaModulo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAlturaPandeo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>