#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adsisplus.Cotyrsa.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbTyrsa")]
	public partial class MarcosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public MarcosDataContext() : 
				base(global::Adsisplus.Cotyrsa.DataAccess.Properties.Settings.Default.dbTyrsaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MarcosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarcosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarcosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarcosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FactorMarcoSP> FactorMarcoSP
		{
			get
			{
				return this.GetTable<FactorMarcoSP>();
			}
		}
		
		public System.Data.Linq.Table<CargaMarcoSP> CargaMarcoSP
		{
			get
			{
				return this.GetTable<CargaMarcoSP>();
			}
		}
		
		public System.Data.Linq.Table<CargaPosteSP> CargaPosteSP
		{
			get
			{
				return this.GetTable<CargaPosteSP>();
			}
		}
		
		public System.Data.Linq.Table<entSeleccionMarco> entSeleccionMarco
		{
			get
			{
				return this.GetTable<entSeleccionMarco>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_RelSistemaCargaMarcoPoste")]
		public ISingleResult<stp_RelSistemaCargaMarcoPosteResult> stp_RelSistemaCargaMarcoPoste([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintSistemaCargaMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intSubProductoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCargaPosteID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCargaMarcoID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sintSistemaCargaMarcoID, intSubProductoID, intCargaPosteID, intCargaMarcoID);
			return ((ISingleResult<stp_RelSistemaCargaMarcoPosteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ActualizaFactorMarco")]
		public ISingleResult<stp_ActualizaFactorMarcoResult> stp_ActualizaFactorMarco([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintFondoMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decCostoLamina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decCostoSolera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactorAcero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> tinOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sintFondoMarcoID, decCostoLamina, decCostoSolera, decFactorAcero, tinOpcion);
			return ((ISingleResult<stp_ActualizaFactorMarcoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarCatFactorMarco")]
		public ISingleResult<FactorMarcoSP> stp_ListarCatFactorMarco()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<FactorMarcoSP>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarCatCargaMarco")]
		public ISingleResult<CargaMarcoSP> stp_ListarCatCargaMarco([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCargaMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintTipoMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCalibreAceroID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCargaMarcoID, sintTipoMarcoID, intCalibreAceroID);
			return ((ISingleResult<CargaMarcoSP>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarCatCargaPoste")]
		public ISingleResult<CargaPosteSP> stp_ListarCatCargaPoste([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCargaPosteID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintTipoMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCalibreAceroID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCargaPosteID, sintTipoMarcoID, intCalibreAceroID);
			return ((ISingleResult<CargaPosteSP>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ConfiguraMarco")]
		public ISingleResult<stp_ConfiguraMarcoResult> stp_ConfiguraMarco([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intConfiguraMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intElementoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintTipoMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intAlturaMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintFondoMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intSKUID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintFactorMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,4)")] System.Nullable<decimal> decFondoMarco)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intConfiguraMarcoID, intElementoID, sintTipoMarcoID, intAlturaMarcoID, sintFondoMarcoID, intSKUID, sintFactorMarcoID, decFondoMarco);
			return ((ISingleResult<stp_ConfiguraMarcoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_setFondoMarco")]
		public ISingleResult<stp_setFondoMarcoResult> stp_setFondoMarco([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sintFondoMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor5, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor7, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor9, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor11, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor13, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor15, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor17, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFactor18)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sintFondoMarcoID, decFactor1, decFactor2, decFactor3, decFactor5, decFactor7, decFactor9, decFactor11, decFactor13, decFactor15, decFactor17, decFactor18);
			return ((ISingleResult<stp_setFondoMarcoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarFondoMarco")]
		public ISingleResult<stp_ListarFondoMarcoResult> stp_ListarFondoMarco()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<stp_ListarFondoMarcoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarDatosSeleccionMarco")]
		public ISingleResult<stp_ListarDatosSeleccionMarcoResult> stp_ListarDatosSeleccionMarco([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intSeleccionMarcoID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intSeleccionMarcoID);
			return ((ISingleResult<stp_ListarDatosSeleccionMarcoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarDatosPantallaMarco")]
		public ISingleResult<stp_ListarDatosPantallaMarcoResult> stp_ListarDatosPantallaMarco([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCotizacionID);
			return ((ISingleResult<stp_ListarDatosPantallaMarcoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarSeleccionMarco")]
		public ISingleResult<entSeleccionMarco> stp_ListarSeleccionMarco([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decCapacidadCarga, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decAlturaPandeo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decFondo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decAlturaMarco, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sistema", DbType="SmallInt")] System.Nullable<short> sistema, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitEstructural)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), decCapacidadCarga, decAlturaPandeo, decFondo, decAlturaMarco, sistema, bitEstructural);
			return ((ISingleResult<entSeleccionMarco>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_setSeleccionMarco")]
		public ISingleResult<stp_setSeleccionMarcoResult> stp_setSeleccionMarco(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intSeleccionMarcoID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intRackID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intConfiguraMarcoID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SKU", DbType="VarChar(50)")] string sKU, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decPesoMarco, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decPrecioUnitario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intMaterialID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decFondo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decAltura, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decAlturaPandeo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decCapacidadMarco, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decFondoMarco, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decAlturaMarco, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> tinOpcionMarco, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decDimensionClaro, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decNNSVS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decMargenExcedente, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decAlturaPiso, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decNNSV, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decNNPVS, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decCargaModulo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> decAlturaPandeoRack, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitActivo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> tinOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intSeleccionMarcoID, intRackID, intCotizacionID, intConfiguraMarcoID, sKU, decPesoMarco, decPrecioUnitario, intTipoID, intMaterialID, decFondo, decAltura, decAlturaPandeo, decCapacidadMarco, decFondoMarco, decAlturaMarco, tinOpcionMarco, decDimensionClaro, decNNSVS, decMargenExcedente, decAlturaPiso, decNNSV, decNNPVS, decCargaModulo, decAlturaPandeoRack, bitActivo, tinOpcion);
			return ((ISingleResult<stp_setSeleccionMarcoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarDatosMarco")]
		public ISingleResult<stp_ListarDatosMarcoResult> stp_ListarDatosMarco([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatoMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intElementoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintPinturaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDetCotizacionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intDatoMarcoID, intCotizacionID, intElementoID, sintPinturaID, intDetCotizacionID);
			return ((ISingleResult<stp_ListarDatosMarcoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class FactorMarcoSP
	{
		
		private short _sintFactorMarcoID;
		
		private string _vchDescCorta;
		
		private string _vchContanteMarco;
		
		private decimal _decCosto;
		
		private System.DateTime _datFechaAlta;
		
		private bool _bitActivo;
		
		public FactorMarcoSP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintFactorMarcoID")]
		public short sintFactorMarcoID
		{
			get
			{
				return this._sintFactorMarcoID;
			}
			set
			{
				if ((this._sintFactorMarcoID != value))
				{
					this._sintFactorMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescCorta", CanBeNull=false)]
		public string vchDescCorta
		{
			get
			{
				return this._vchDescCorta;
			}
			set
			{
				if ((this._vchDescCorta != value))
				{
					this._vchDescCorta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchContanteMarco", CanBeNull=false)]
		public string vchContanteMarco
		{
			get
			{
				return this._vchContanteMarco;
			}
			set
			{
				if ((this._vchContanteMarco != value))
				{
					this._vchContanteMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCosto")]
		public decimal decCosto
		{
			get
			{
				return this._decCosto;
			}
			set
			{
				if ((this._decCosto != value))
				{
					this._decCosto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFechaAlta")]
		public System.DateTime datFechaAlta
		{
			get
			{
				return this._datFechaAlta;
			}
			set
			{
				if ((this._datFechaAlta != value))
				{
					this._datFechaAlta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo")]
		public bool bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CargaMarcoSP
	{
		
		private bool _bitActivo;
		
		private decimal _decAlturaPandeoM;
		
		private int _intAlturaPandeoIN;
		
		private int _intCapacidadPeso;
		
		private int _intCargaMarcoID;
		
		private string _vchCalibreAcero;
		
		private string _vchFondoMercadoA;
		
		private string _vchFondoMercadoB;
		
		private string _vchFondoTyrsa;
		
		private string _vchFrenteMercadoA;
		
		private string _vchFrenteMercadoB;
		
		private string _vchFrenteTyrsa;
		
		private string _vchTipoMarcoTyrsa;
		
		public CargaMarcoSP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo")]
		public bool bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPandeoM")]
		public decimal decAlturaPandeoM
		{
			get
			{
				return this._decAlturaPandeoM;
			}
			set
			{
				if ((this._decAlturaPandeoM != value))
				{
					this._decAlturaPandeoM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAlturaPandeoIN")]
		public int intAlturaPandeoIN
		{
			get
			{
				return this._intAlturaPandeoIN;
			}
			set
			{
				if ((this._intAlturaPandeoIN != value))
				{
					this._intAlturaPandeoIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCapacidadPeso")]
		public int intCapacidadPeso
		{
			get
			{
				return this._intCapacidadPeso;
			}
			set
			{
				if ((this._intCapacidadPeso != value))
				{
					this._intCapacidadPeso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCargaMarcoID")]
		public int intCargaMarcoID
		{
			get
			{
				return this._intCargaMarcoID;
			}
			set
			{
				if ((this._intCargaMarcoID != value))
				{
					this._intCargaMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCalibreAcero", CanBeNull=false)]
		public string vchCalibreAcero
		{
			get
			{
				return this._vchCalibreAcero;
			}
			set
			{
				if ((this._vchCalibreAcero != value))
				{
					this._vchCalibreAcero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoMercadoA", CanBeNull=false)]
		public string vchFondoMercadoA
		{
			get
			{
				return this._vchFondoMercadoA;
			}
			set
			{
				if ((this._vchFondoMercadoA != value))
				{
					this._vchFondoMercadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoMercadoB", CanBeNull=false)]
		public string vchFondoMercadoB
		{
			get
			{
				return this._vchFondoMercadoB;
			}
			set
			{
				if ((this._vchFondoMercadoB != value))
				{
					this._vchFondoMercadoB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoTyrsa", CanBeNull=false)]
		public string vchFondoTyrsa
		{
			get
			{
				return this._vchFondoTyrsa;
			}
			set
			{
				if ((this._vchFondoTyrsa != value))
				{
					this._vchFondoTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFrenteMercadoA", CanBeNull=false)]
		public string vchFrenteMercadoA
		{
			get
			{
				return this._vchFrenteMercadoA;
			}
			set
			{
				if ((this._vchFrenteMercadoA != value))
				{
					this._vchFrenteMercadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFrenteMercadoB", CanBeNull=false)]
		public string vchFrenteMercadoB
		{
			get
			{
				return this._vchFrenteMercadoB;
			}
			set
			{
				if ((this._vchFrenteMercadoB != value))
				{
					this._vchFrenteMercadoB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFrenteTyrsa", CanBeNull=false)]
		public string vchFrenteTyrsa
		{
			get
			{
				return this._vchFrenteTyrsa;
			}
			set
			{
				if ((this._vchFrenteTyrsa != value))
				{
					this._vchFrenteTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipoMarcoTyrsa", CanBeNull=false)]
		public string vchTipoMarcoTyrsa
		{
			get
			{
				return this._vchTipoMarcoTyrsa;
			}
			set
			{
				if ((this._vchTipoMarcoTyrsa != value))
				{
					this._vchTipoMarcoTyrsa = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class CargaPosteSP
	{
		
		private bool _bitActivo;
		
		private int _intCargaPosteID;
		
		private short _sintTipoMarcoID;
		
		private string _vchTipoMarcoTyrsa;
		
		private int _intCalibreAceroID;
		
		private string _vchCalibreAcero;
		
		private string _vchFrenteTyrsa;
		
		private string _vchFrenteMercadoA;
		
		private string _vchFrenteMercadoB;
		
		private string _vchFondoTyrsa;
		
		private string _vchFondoMercadoA;
		
		private string _vchFondoMercadoB;
		
		private decimal _decAlturaPandeoM;
		
		private int _intAlturaPandeoIN;
		
		private int _intCapacidadPeso;
		
		public CargaPosteSP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo")]
		public bool bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCargaPosteID")]
		public int intCargaPosteID
		{
			get
			{
				return this._intCargaPosteID;
			}
			set
			{
				if ((this._intCargaPosteID != value))
				{
					this._intCargaPosteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintTipoMarcoID")]
		public short sintTipoMarcoID
		{
			get
			{
				return this._sintTipoMarcoID;
			}
			set
			{
				if ((this._sintTipoMarcoID != value))
				{
					this._sintTipoMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipoMarcoTyrsa", CanBeNull=false)]
		public string vchTipoMarcoTyrsa
		{
			get
			{
				return this._vchTipoMarcoTyrsa;
			}
			set
			{
				if ((this._vchTipoMarcoTyrsa != value))
				{
					this._vchTipoMarcoTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCalibreAceroID")]
		public int intCalibreAceroID
		{
			get
			{
				return this._intCalibreAceroID;
			}
			set
			{
				if ((this._intCalibreAceroID != value))
				{
					this._intCalibreAceroID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCalibreAcero", CanBeNull=false)]
		public string vchCalibreAcero
		{
			get
			{
				return this._vchCalibreAcero;
			}
			set
			{
				if ((this._vchCalibreAcero != value))
				{
					this._vchCalibreAcero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFrenteTyrsa", CanBeNull=false)]
		public string vchFrenteTyrsa
		{
			get
			{
				return this._vchFrenteTyrsa;
			}
			set
			{
				if ((this._vchFrenteTyrsa != value))
				{
					this._vchFrenteTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFrenteMercadoA", CanBeNull=false)]
		public string vchFrenteMercadoA
		{
			get
			{
				return this._vchFrenteMercadoA;
			}
			set
			{
				if ((this._vchFrenteMercadoA != value))
				{
					this._vchFrenteMercadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFrenteMercadoB", CanBeNull=false)]
		public string vchFrenteMercadoB
		{
			get
			{
				return this._vchFrenteMercadoB;
			}
			set
			{
				if ((this._vchFrenteMercadoB != value))
				{
					this._vchFrenteMercadoB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoTyrsa", CanBeNull=false)]
		public string vchFondoTyrsa
		{
			get
			{
				return this._vchFondoTyrsa;
			}
			set
			{
				if ((this._vchFondoTyrsa != value))
				{
					this._vchFondoTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoMercadoA", CanBeNull=false)]
		public string vchFondoMercadoA
		{
			get
			{
				return this._vchFondoMercadoA;
			}
			set
			{
				if ((this._vchFondoMercadoA != value))
				{
					this._vchFondoMercadoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoMercadoB", CanBeNull=false)]
		public string vchFondoMercadoB
		{
			get
			{
				return this._vchFondoMercadoB;
			}
			set
			{
				if ((this._vchFondoMercadoB != value))
				{
					this._vchFondoMercadoB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPandeoM")]
		public decimal decAlturaPandeoM
		{
			get
			{
				return this._decAlturaPandeoM;
			}
			set
			{
				if ((this._decAlturaPandeoM != value))
				{
					this._decAlturaPandeoM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAlturaPandeoIN")]
		public int intAlturaPandeoIN
		{
			get
			{
				return this._intAlturaPandeoIN;
			}
			set
			{
				if ((this._intAlturaPandeoIN != value))
				{
					this._intAlturaPandeoIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCapacidadPeso")]
		public int intCapacidadPeso
		{
			get
			{
				return this._intCapacidadPeso;
			}
			set
			{
				if ((this._intCapacidadPeso != value))
				{
					this._intCapacidadPeso = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class entSeleccionMarco
	{
		
		private string _SKU;
		
		private int _intConfiguraMarcoID;
		
		private decimal _decPesoMarco;
		
		private decimal _decPrecioUnitario;
		
		private string _vchTipo;
		
		private string _vchMaterial;
		
		private decimal _decFondo;
		
		private decimal _decAltura;
		
		private decimal _decAlturaPandeo;
		
		private decimal _decCapacidadMarco;
		
		private int _intTipoID;
		
		private int _intMaterialID;
		
		public entSeleccionMarco()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", CanBeNull=false)]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this._SKU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intConfiguraMarcoID")]
		public int intConfiguraMarcoID
		{
			get
			{
				return this._intConfiguraMarcoID;
			}
			set
			{
				if ((this._intConfiguraMarcoID != value))
				{
					this._intConfiguraMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPesoMarco")]
		public decimal decPesoMarco
		{
			get
			{
				return this._decPesoMarco;
			}
			set
			{
				if ((this._decPesoMarco != value))
				{
					this._decPesoMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioUnitario")]
		public decimal decPrecioUnitario
		{
			get
			{
				return this._decPrecioUnitario;
			}
			set
			{
				if ((this._decPrecioUnitario != value))
				{
					this._decPrecioUnitario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipo", CanBeNull=false)]
		public string vchTipo
		{
			get
			{
				return this._vchTipo;
			}
			set
			{
				if ((this._vchTipo != value))
				{
					this._vchTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMaterial", CanBeNull=false)]
		public string vchMaterial
		{
			get
			{
				return this._vchMaterial;
			}
			set
			{
				if ((this._vchMaterial != value))
				{
					this._vchMaterial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decFondo")]
		public decimal decFondo
		{
			get
			{
				return this._decFondo;
			}
			set
			{
				if ((this._decFondo != value))
				{
					this._decFondo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAltura")]
		public decimal decAltura
		{
			get
			{
				return this._decAltura;
			}
			set
			{
				if ((this._decAltura != value))
				{
					this._decAltura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPandeo")]
		public decimal decAlturaPandeo
		{
			get
			{
				return this._decAlturaPandeo;
			}
			set
			{
				if ((this._decAlturaPandeo != value))
				{
					this._decAlturaPandeo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCapacidadMarco")]
		public decimal decCapacidadMarco
		{
			get
			{
				return this._decCapacidadMarco;
			}
			set
			{
				if ((this._decCapacidadMarco != value))
				{
					this._decCapacidadMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoID")]
		public int intTipoID
		{
			get
			{
				return this._intTipoID;
			}
			set
			{
				if ((this._intTipoID != value))
				{
					this._intTipoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intMaterialID")]
		public int intMaterialID
		{
			get
			{
				return this._intMaterialID;
			}
			set
			{
				if ((this._intMaterialID != value))
				{
					this._intMaterialID = value;
				}
			}
		}
	}
	
	public partial class stp_RelSistemaCargaMarcoPosteResult
	{
		
		private short _sintSistemaCargaMarcoID;
		
		private string _vchDescripcionSub;
		
		private string _vchFondoTyrsaPoste;
		
		private string _vchFondoTyrsaMarco;
		
		private System.Nullable<bool> _bitActivo;
		
		public stp_RelSistemaCargaMarcoPosteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintSistemaCargaMarcoID", DbType="SmallInt NOT NULL")]
		public short sintSistemaCargaMarcoID
		{
			get
			{
				return this._sintSistemaCargaMarcoID;
			}
			set
			{
				if ((this._sintSistemaCargaMarcoID != value))
				{
					this._sintSistemaCargaMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcionSub", DbType="VarChar(25)")]
		public string vchDescripcionSub
		{
			get
			{
				return this._vchDescripcionSub;
			}
			set
			{
				if ((this._vchDescripcionSub != value))
				{
					this._vchDescripcionSub = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoTyrsaPoste", DbType="VarChar(25)")]
		public string vchFondoTyrsaPoste
		{
			get
			{
				return this._vchFondoTyrsaPoste;
			}
			set
			{
				if ((this._vchFondoTyrsaPoste != value))
				{
					this._vchFondoTyrsaPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoTyrsaMarco", DbType="VarChar(25)")]
		public string vchFondoTyrsaMarco
		{
			get
			{
				return this._vchFondoTyrsaMarco;
			}
			set
			{
				if ((this._vchFondoTyrsaMarco != value))
				{
					this._vchFondoTyrsaMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
	
	public partial class stp_ActualizaFactorMarcoResult
	{
		
		private string _vchResultado;
		
		private string _vchDescripcion;
		
		public stp_ActualizaFactorMarcoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchResultado", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string vchResultado
		{
			get
			{
				return this._vchResultado;
			}
			set
			{
				if ((this._vchResultado != value))
				{
					this._vchResultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="NVarChar(4000)")]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
	
	public partial class stp_ConfiguraMarcoResult
	{
		
		private int _intConfiguraMarcoID;
		
		private string _vchElemento;
		
		private string _vchTipoMarcoTyrsa;
		
		private System.Nullable<short> _sintSKU;
		
		private System.Nullable<decimal> _decAlturaMarco;
		
		private System.Nullable<decimal> _decFondoMarco;
		
		private string _vchContanteMarco;
		
		private System.Nullable<decimal> _decCalibre;
		
		private System.Nullable<decimal> _decSolera;
		
		private System.Nullable<decimal> _decTotalKilo;
		
		private System.Nullable<decimal> _decPrecioTyrsa;
		
		private System.Nullable<decimal> _decRelacionPrecios;
		
		private System.Nullable<decimal> _decPrecioTyrsaMetro;
		
		private System.Nullable<decimal> _decPrecioTyrsaKg;
		
		private System.Nullable<short> _sintNumPosteReq;
		
		private System.Nullable<short> _sintNumTravesanio;
		
		private System.Nullable<short> _sintDiagonalLarga;
		
		private System.Nullable<short> _sintDiagonalCorta;
		
		private System.Nullable<decimal> _decPesoCobroLam14;
		
		private System.Nullable<decimal> _decPesoTotal;
		
		private System.Nullable<decimal> _decPintaPoste;
		
		private System.Nullable<decimal> _decPintaTravesanio;
		
		private System.Nullable<decimal> _decPintaDiagonalLarga;
		
		private System.Nullable<decimal> _decPintaDiagonalCorta;
		
		private System.Nullable<decimal> _decPintaPlacaBase;
		
		private System.Nullable<decimal> _decTotalMarcoCompleto;
		
		private System.Nullable<decimal> _decCalibreDosCaras;
		
		private System.Nullable<bool> _bitActivo;
		
		public stp_ConfiguraMarcoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intConfiguraMarcoID", DbType="Int NOT NULL")]
		public int intConfiguraMarcoID
		{
			get
			{
				return this._intConfiguraMarcoID;
			}
			set
			{
				if ((this._intConfiguraMarcoID != value))
				{
					this._intConfiguraMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchElemento", DbType="VarChar(25)")]
		public string vchElemento
		{
			get
			{
				return this._vchElemento;
			}
			set
			{
				if ((this._vchElemento != value))
				{
					this._vchElemento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipoMarcoTyrsa", DbType="VarChar(25)")]
		public string vchTipoMarcoTyrsa
		{
			get
			{
				return this._vchTipoMarcoTyrsa;
			}
			set
			{
				if ((this._vchTipoMarcoTyrsa != value))
				{
					this._vchTipoMarcoTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintSKU", DbType="SmallInt")]
		public System.Nullable<short> sintSKU
		{
			get
			{
				return this._sintSKU;
			}
			set
			{
				if ((this._sintSKU != value))
				{
					this._sintSKU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaMarco", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decAlturaMarco
		{
			get
			{
				return this._decAlturaMarco;
			}
			set
			{
				if ((this._decAlturaMarco != value))
				{
					this._decAlturaMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decFondoMarco", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> decFondoMarco
		{
			get
			{
				return this._decFondoMarco;
			}
			set
			{
				if ((this._decFondoMarco != value))
				{
					this._decFondoMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchContanteMarco", DbType="VarChar(50)")]
		public string vchContanteMarco
		{
			get
			{
				return this._vchContanteMarco;
			}
			set
			{
				if ((this._vchContanteMarco != value))
				{
					this._vchContanteMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCalibre", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decCalibre
		{
			get
			{
				return this._decCalibre;
			}
			set
			{
				if ((this._decCalibre != value))
				{
					this._decCalibre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decSolera", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decSolera
		{
			get
			{
				return this._decSolera;
			}
			set
			{
				if ((this._decSolera != value))
				{
					this._decSolera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decTotalKilo", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decTotalKilo
		{
			get
			{
				return this._decTotalKilo;
			}
			set
			{
				if ((this._decTotalKilo != value))
				{
					this._decTotalKilo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsa", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decPrecioTyrsa
		{
			get
			{
				return this._decPrecioTyrsa;
			}
			set
			{
				if ((this._decPrecioTyrsa != value))
				{
					this._decPrecioTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decRelacionPrecios", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decRelacionPrecios
		{
			get
			{
				return this._decRelacionPrecios;
			}
			set
			{
				if ((this._decRelacionPrecios != value))
				{
					this._decRelacionPrecios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsaMetro", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decPrecioTyrsaMetro
		{
			get
			{
				return this._decPrecioTyrsaMetro;
			}
			set
			{
				if ((this._decPrecioTyrsaMetro != value))
				{
					this._decPrecioTyrsaMetro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsaKg", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decPrecioTyrsaKg
		{
			get
			{
				return this._decPrecioTyrsaKg;
			}
			set
			{
				if ((this._decPrecioTyrsaKg != value))
				{
					this._decPrecioTyrsaKg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintNumPosteReq", DbType="SmallInt")]
		public System.Nullable<short> sintNumPosteReq
		{
			get
			{
				return this._sintNumPosteReq;
			}
			set
			{
				if ((this._sintNumPosteReq != value))
				{
					this._sintNumPosteReq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintNumTravesanio", DbType="SmallInt")]
		public System.Nullable<short> sintNumTravesanio
		{
			get
			{
				return this._sintNumTravesanio;
			}
			set
			{
				if ((this._sintNumTravesanio != value))
				{
					this._sintNumTravesanio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintDiagonalLarga", DbType="SmallInt")]
		public System.Nullable<short> sintDiagonalLarga
		{
			get
			{
				return this._sintDiagonalLarga;
			}
			set
			{
				if ((this._sintDiagonalLarga != value))
				{
					this._sintDiagonalLarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintDiagonalCorta", DbType="SmallInt")]
		public System.Nullable<short> sintDiagonalCorta
		{
			get
			{
				return this._sintDiagonalCorta;
			}
			set
			{
				if ((this._sintDiagonalCorta != value))
				{
					this._sintDiagonalCorta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPesoCobroLam14", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decPesoCobroLam14
		{
			get
			{
				return this._decPesoCobroLam14;
			}
			set
			{
				if ((this._decPesoCobroLam14 != value))
				{
					this._decPesoCobroLam14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPesoTotal", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decPesoTotal
		{
			get
			{
				return this._decPesoTotal;
			}
			set
			{
				if ((this._decPesoTotal != value))
				{
					this._decPesoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPintaPoste", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decPintaPoste
		{
			get
			{
				return this._decPintaPoste;
			}
			set
			{
				if ((this._decPintaPoste != value))
				{
					this._decPintaPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPintaTravesanio", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decPintaTravesanio
		{
			get
			{
				return this._decPintaTravesanio;
			}
			set
			{
				if ((this._decPintaTravesanio != value))
				{
					this._decPintaTravesanio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPintaDiagonalLarga", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decPintaDiagonalLarga
		{
			get
			{
				return this._decPintaDiagonalLarga;
			}
			set
			{
				if ((this._decPintaDiagonalLarga != value))
				{
					this._decPintaDiagonalLarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPintaDiagonalCorta", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decPintaDiagonalCorta
		{
			get
			{
				return this._decPintaDiagonalCorta;
			}
			set
			{
				if ((this._decPintaDiagonalCorta != value))
				{
					this._decPintaDiagonalCorta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPintaPlacaBase", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decPintaPlacaBase
		{
			get
			{
				return this._decPintaPlacaBase;
			}
			set
			{
				if ((this._decPintaPlacaBase != value))
				{
					this._decPintaPlacaBase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decTotalMarcoCompleto", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decTotalMarcoCompleto
		{
			get
			{
				return this._decTotalMarcoCompleto;
			}
			set
			{
				if ((this._decTotalMarcoCompleto != value))
				{
					this._decTotalMarcoCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCalibreDosCaras", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decCalibreDosCaras
		{
			get
			{
				return this._decCalibreDosCaras;
			}
			set
			{
				if ((this._decCalibreDosCaras != value))
				{
					this._decCalibreDosCaras = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
	
	public partial class stp_setFondoMarcoResult
	{
		
		private string _vchResultado;
		
		private string _vchDescripcion;
		
		public stp_setFondoMarcoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchResultado", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string vchResultado
		{
			get
			{
				return this._vchResultado;
			}
			set
			{
				if ((this._vchResultado != value))
				{
					this._vchResultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
	
	public partial class stp_ListarFondoMarcoResult
	{
		
		private System.Nullable<decimal> _decFondoMarco;
		
		public stp_ListarFondoMarcoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decFondoMarco", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> decFondoMarco
		{
			get
			{
				return this._decFondoMarco;
			}
			set
			{
				if ((this._decFondoMarco != value))
				{
					this._decFondoMarco = value;
				}
			}
		}
	}
	
	public partial class stp_ListarDatosSeleccionMarcoResult
	{
		
		private int _intSeleccionMarcoID;
		
		private string _SKU;
		
		private System.Nullable<decimal> _decPesoMarco;
		
		private System.Nullable<decimal> _decPrecioUnitario;
		
		private System.Nullable<int> _intTipo;
		
		private string _vchTipo;
		
		private System.Nullable<int> _intMaterialID;
		
		private string _vchMaterialID;
		
		private System.Nullable<decimal> _decFondo;
		
		private System.Nullable<decimal> _decAltura;
		
		private System.Nullable<decimal> _decAlturaPandeo;
		
		private System.Nullable<decimal> _decCapacidadMarco;
		
		private System.Nullable<bool> _bitActivo;
		
		public stp_ListarDatosSeleccionMarcoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSeleccionMarcoID", DbType="Int NOT NULL")]
		public int intSeleccionMarcoID
		{
			get
			{
				return this._intSeleccionMarcoID;
			}
			set
			{
				if ((this._intSeleccionMarcoID != value))
				{
					this._intSeleccionMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="VarChar(50)")]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this._SKU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPesoMarco", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decPesoMarco
		{
			get
			{
				return this._decPesoMarco;
			}
			set
			{
				if ((this._decPesoMarco != value))
				{
					this._decPesoMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioUnitario", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decPrecioUnitario
		{
			get
			{
				return this._decPrecioUnitario;
			}
			set
			{
				if ((this._decPrecioUnitario != value))
				{
					this._decPrecioUnitario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipo", DbType="Int")]
		public System.Nullable<int> intTipo
		{
			get
			{
				return this._intTipo;
			}
			set
			{
				if ((this._intTipo != value))
				{
					this._intTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipo", DbType="VarChar(25)")]
		public string vchTipo
		{
			get
			{
				return this._vchTipo;
			}
			set
			{
				if ((this._vchTipo != value))
				{
					this._vchTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intMaterialID", DbType="Int")]
		public System.Nullable<int> intMaterialID
		{
			get
			{
				return this._intMaterialID;
			}
			set
			{
				if ((this._intMaterialID != value))
				{
					this._intMaterialID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMaterialID", DbType="VarChar(50)")]
		public string vchMaterialID
		{
			get
			{
				return this._vchMaterialID;
			}
			set
			{
				if ((this._vchMaterialID != value))
				{
					this._vchMaterialID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decFondo", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decFondo
		{
			get
			{
				return this._decFondo;
			}
			set
			{
				if ((this._decFondo != value))
				{
					this._decFondo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAltura", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAltura
		{
			get
			{
				return this._decAltura;
			}
			set
			{
				if ((this._decAltura != value))
				{
					this._decAltura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPandeo", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAlturaPandeo
		{
			get
			{
				return this._decAlturaPandeo;
			}
			set
			{
				if ((this._decAlturaPandeo != value))
				{
					this._decAlturaPandeo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCapacidadMarco", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decCapacidadMarco
		{
			get
			{
				return this._decCapacidadMarco;
			}
			set
			{
				if ((this._decCapacidadMarco != value))
				{
					this._decCapacidadMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
	
	public partial class stp_ListarDatosPantallaMarcoResult
	{
		
		private int _intRackID;
		
		private System.Nullable<int> _intCotizacionID;
		
		private System.Nullable<int> _intSeleccionMarcoID;
		
		private System.Nullable<decimal> _decFondoMarco;
		
		private System.Nullable<byte> _tinOpcionMarco;
		
		private System.Nullable<decimal> _decDimensionClaro;
		
		private System.Nullable<decimal> _decNNSVS;
		
		private System.Nullable<decimal> _decMargenExcedente;
		
		private System.Nullable<decimal> _decAlturaMarco;
		
		private System.Nullable<decimal> _decAlturaPiso;
		
		private System.Nullable<decimal> _decNNSV;
		
		private System.Nullable<decimal> _decNNPVS;
		
		private System.Nullable<decimal> _decCargaModulo;
		
		private System.Nullable<decimal> _decAlturaPandeo;
		
		public stp_ListarDatosPantallaMarcoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intRackID", DbType="Int NOT NULL")]
		public int intRackID
		{
			get
			{
				return this._intRackID;
			}
			set
			{
				if ((this._intRackID != value))
				{
					this._intRackID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCotizacionID", DbType="Int")]
		public System.Nullable<int> intCotizacionID
		{
			get
			{
				return this._intCotizacionID;
			}
			set
			{
				if ((this._intCotizacionID != value))
				{
					this._intCotizacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSeleccionMarcoID", DbType="Int")]
		public System.Nullable<int> intSeleccionMarcoID
		{
			get
			{
				return this._intSeleccionMarcoID;
			}
			set
			{
				if ((this._intSeleccionMarcoID != value))
				{
					this._intSeleccionMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decFondoMarco", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decFondoMarco
		{
			get
			{
				return this._decFondoMarco;
			}
			set
			{
				if ((this._decFondoMarco != value))
				{
					this._decFondoMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinOpcionMarco", DbType="TinyInt")]
		public System.Nullable<byte> tinOpcionMarco
		{
			get
			{
				return this._tinOpcionMarco;
			}
			set
			{
				if ((this._tinOpcionMarco != value))
				{
					this._tinOpcionMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decDimensionClaro", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decDimensionClaro
		{
			get
			{
				return this._decDimensionClaro;
			}
			set
			{
				if ((this._decDimensionClaro != value))
				{
					this._decDimensionClaro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decNNSVS", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decNNSVS
		{
			get
			{
				return this._decNNSVS;
			}
			set
			{
				if ((this._decNNSVS != value))
				{
					this._decNNSVS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decMargenExcedente", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decMargenExcedente
		{
			get
			{
				return this._decMargenExcedente;
			}
			set
			{
				if ((this._decMargenExcedente != value))
				{
					this._decMargenExcedente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaMarco", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAlturaMarco
		{
			get
			{
				return this._decAlturaMarco;
			}
			set
			{
				if ((this._decAlturaMarco != value))
				{
					this._decAlturaMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPiso", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAlturaPiso
		{
			get
			{
				return this._decAlturaPiso;
			}
			set
			{
				if ((this._decAlturaPiso != value))
				{
					this._decAlturaPiso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decNNSV", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decNNSV
		{
			get
			{
				return this._decNNSV;
			}
			set
			{
				if ((this._decNNSV != value))
				{
					this._decNNSV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decNNPVS", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decNNPVS
		{
			get
			{
				return this._decNNPVS;
			}
			set
			{
				if ((this._decNNPVS != value))
				{
					this._decNNPVS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCargaModulo", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decCargaModulo
		{
			get
			{
				return this._decCargaModulo;
			}
			set
			{
				if ((this._decCargaModulo != value))
				{
					this._decCargaModulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPandeo", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAlturaPandeo
		{
			get
			{
				return this._decAlturaPandeo;
			}
			set
			{
				if ((this._decAlturaPandeo != value))
				{
					this._decAlturaPandeo = value;
				}
			}
		}
	}
	
	public partial class stp_setSeleccionMarcoResult
	{
		
		private string _vchResultado;
		
		private string _vchDescripcion;
		
		public stp_setSeleccionMarcoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchResultado", DbType="VarChar(12)")]
		public string vchResultado
		{
			get
			{
				return this._vchResultado;
			}
			set
			{
				if ((this._vchResultado != value))
				{
					this._vchResultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(57) NOT NULL", CanBeNull=false)]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
	
	public partial class stp_ListarDatosMarcoResult
	{
		
		private int _intDatoMarcoID;
		
		private System.Nullable<int> _intConfiguraMarcoID;
		
		private System.Nullable<int> _intCotizacionID;
		
		private string _vchFolio;
		
		private string _vchElemento;
		
		private string _vchPintura;
		
		private System.Nullable<decimal> _decMedidaFondo;
		
		private System.Nullable<decimal> _decMedidaAlto;
		
		private System.Nullable<bool> _bitDobleMonten;
		
		private System.Nullable<int> _intNumeroNivelSobreViga;
		
		private System.Nullable<decimal> _decAlturaPandeo;
		
		private System.Nullable<decimal> _decCapacidadxNivel;
		
		private System.Nullable<short> _sintCantidad;
		
		private System.Nullable<bool> _bitActivo;
		
		public stp_ListarDatosMarcoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDatoMarcoID", DbType="Int NOT NULL")]
		public int intDatoMarcoID
		{
			get
			{
				return this._intDatoMarcoID;
			}
			set
			{
				if ((this._intDatoMarcoID != value))
				{
					this._intDatoMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intConfiguraMarcoID", DbType="Int")]
		public System.Nullable<int> intConfiguraMarcoID
		{
			get
			{
				return this._intConfiguraMarcoID;
			}
			set
			{
				if ((this._intConfiguraMarcoID != value))
				{
					this._intConfiguraMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCotizacionID", DbType="Int")]
		public System.Nullable<int> intCotizacionID
		{
			get
			{
				return this._intCotizacionID;
			}
			set
			{
				if ((this._intCotizacionID != value))
				{
					this._intCotizacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFolio", DbType="VarChar(250)")]
		public string vchFolio
		{
			get
			{
				return this._vchFolio;
			}
			set
			{
				if ((this._vchFolio != value))
				{
					this._vchFolio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchElemento", DbType="VarChar(25)")]
		public string vchElemento
		{
			get
			{
				return this._vchElemento;
			}
			set
			{
				if ((this._vchElemento != value))
				{
					this._vchElemento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchPintura", DbType="VarChar(25)")]
		public string vchPintura
		{
			get
			{
				return this._vchPintura;
			}
			set
			{
				if ((this._vchPintura != value))
				{
					this._vchPintura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decMedidaFondo", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> decMedidaFondo
		{
			get
			{
				return this._decMedidaFondo;
			}
			set
			{
				if ((this._decMedidaFondo != value))
				{
					this._decMedidaFondo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decMedidaAlto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> decMedidaAlto
		{
			get
			{
				return this._decMedidaAlto;
			}
			set
			{
				if ((this._decMedidaAlto != value))
				{
					this._decMedidaAlto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitDobleMonten", DbType="Bit")]
		public System.Nullable<bool> bitDobleMonten
		{
			get
			{
				return this._bitDobleMonten;
			}
			set
			{
				if ((this._bitDobleMonten != value))
				{
					this._bitDobleMonten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intNumeroNivelSobreViga", DbType="Int")]
		public System.Nullable<int> intNumeroNivelSobreViga
		{
			get
			{
				return this._intNumeroNivelSobreViga;
			}
			set
			{
				if ((this._intNumeroNivelSobreViga != value))
				{
					this._intNumeroNivelSobreViga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPandeo", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> decAlturaPandeo
		{
			get
			{
				return this._decAlturaPandeo;
			}
			set
			{
				if ((this._decAlturaPandeo != value))
				{
					this._decAlturaPandeo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCapacidadxNivel", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> decCapacidadxNivel
		{
			get
			{
				return this._decCapacidadxNivel;
			}
			set
			{
				if ((this._decCapacidadxNivel != value))
				{
					this._decCapacidadxNivel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintCantidad", DbType="SmallInt")]
		public System.Nullable<short> sintCantidad
		{
			get
			{
				return this._sintCantidad;
			}
			set
			{
				if ((this._sintCantidad != value))
				{
					this._sintCantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
