<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="ParrillaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_ListarDatosParrilla" Method="stp_ListarDatosParrilla">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosParrillaResult">
      <Column Name="intParrillaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchPintura" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchFolio" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="decFrenteParrilla" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decFondoParrilla" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decCostoParrilla" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decTamanioCuadroParrilla" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="intCantidadParrilla" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>