<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="PerfilDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="" Member="entPerfilCartonFlow">
    <Type Name="entPerfilCartonFlow" Id="ID1">
      <Column Name="sintTipoCartonFlowID" Type="System.Int16" CanBeNull="false" />
      <Column Name="sintCalibre" Type="System.Int16" CanBeNull="false" />
      <Column Name="vchTipoCartonFlow" Type="System.String" CanBeNull="false" />
      <Column Name="decAncho" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decLargo" Type="System.Decimal" CanBeNull="false" />
      <Column Name="sintPesoPieza" Type="System.Int16" CanBeNull="false" />
      <Column Name="decTotalKiloUnitario" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" CanBeNull="false" />
      <Column Name="vchLeyenda" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.stp_ListarPerfilCartonFlow" Method="stp_ListarPerfilCartonFlow">
    <Parameter Name="sintTipoCartonFlowID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCalibreAceroID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decLargoPerfil" Type="System.Decimal" DbType="Decimal(8,2)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.stp_ListarCatPerfilCartonFlow" Method="stp_ListarCatPerfilCartonFlow">
    <ElementType Name="stp_ListarCatPerfilCartonFlowResult">
      <Column Name="sintTipoCartonFlowID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="vchTipoCartonFlow" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosPerfilCartonFlow" Method="stp_ListarDatosPerfilCartonFlow">
    <Parameter Name="intPerfilID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosPerfilCartonFlowResult">
      <Column Name="intPerfilID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sintTipoPerfilID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sintTipoCartonFlowID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCalibreAceroID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decLargo" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decCapacidad" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="intCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchLeyenda" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decPrecioTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decPesoUnitario" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="sintNumXNivel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>