#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adsisplus.Cotyrsa.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbTyrsa")]
	public partial class PersonaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public PersonaDataContext() : 
				base(global::Adsisplus.Cotyrsa.DataAccess.Properties.Settings.Default.dbTyrsaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public PersonaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarDatosPersona")]
		public ISingleResult<stp_ListarDatosPersonaResult> stp_ListarDatosPersona([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intPersonaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoPersonaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intEmpresaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intPersonaID, intTipoPersonaID, intEmpresaID);
			return ((ISingleResult<stp_ListarDatosPersonaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarRelPersonaDireccionEmpresa")]
		public ISingleResult<stp_ListarRelPersonaDireccionEmpresaResult> stp_ListarRelPersonaDireccionEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intPersonaDomEmpreID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intPersonaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDireccionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intEmpresaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intPersonaDomEmpreID, intPersonaID, intDireccionID, intEmpresaID);
			return ((ISingleResult<stp_ListarRelPersonaDireccionEmpresaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_setPersona")]
		public ISingleResult<stp_setPersonaResult> stp_setPersona(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intPersonaID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoPersonaID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intEmpresaID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string vchNombreCompleto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchNombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchApPaterno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchApMaterno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> datFechaNacimiento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string vchLugarNacimiento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(13)")] string vchRFC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(18)")] string vchCURP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintEdad, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string vchTelefono, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(12)")] string vchTelefonoMovil, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string vchMail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitActivo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitCausaRetencion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> tinOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intPersonaID, intTipoPersonaID, intEmpresaID, vchNombreCompleto, vchNombre, vchApPaterno, vchApMaterno, datFechaNacimiento, vchLugarNacimiento, vchRFC, vchCURP, sintEdad, vchTelefono, vchTelefonoMovil, vchMail, bitActivo, bitCausaRetencion, tinOpcion);
			return ((ISingleResult<stp_setPersonaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_setRelaciónPersonaDomicilioEmpresa")]
		public ISingleResult<stp_setRelaciónPersonaDomicilioEmpresaResult> stp_setRelaciónPersonaDomicilioEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intPersonaDomEmpreID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intPersonaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDireccionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intEmpresaID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bitActivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> tinOpcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intPersonaDomEmpreID, intPersonaID, intDireccionID, intEmpresaID, bitActivo, tinOpcion);
			return ((ISingleResult<stp_setRelaciónPersonaDomicilioEmpresaResult>)(result.ReturnValue));
		}
	}
	
	public partial class stp_ListarDatosPersonaResult
	{
		
		private int _intPersonaID;
		
		private string _vchTipoPersona;
		
		private string _vchNombreEmpresa;
		
		private string _vchNombreCompleto;
		
		private string _vchNombre;
		
		private string _vchApPaterno;
		
		private string _vchApMaterno;
		
		private System.Nullable<System.DateTime> _datFechaNacimiento;
		
		private string _vchLugarNacimiento;
		
		private string _vchRFC;
		
		private string _vchCURP;
		
		private System.Nullable<short> _sintEdad;
		
		private string _vchTelefono;
		
		private string _vchTelefonoMovil;
		
		private string _vchMail;
		
		private System.Nullable<bool> _bitActivo;
		
		private System.Nullable<bool> _bitCausaRetencion;
		
		public stp_ListarDatosPersonaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intPersonaID", DbType="Int NOT NULL")]
		public int intPersonaID
		{
			get
			{
				return this._intPersonaID;
			}
			set
			{
				if ((this._intPersonaID != value))
				{
					this._intPersonaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTipoPersona", DbType="VarChar(25)")]
		public string vchTipoPersona
		{
			get
			{
				return this._vchTipoPersona;
			}
			set
			{
				if ((this._vchTipoPersona != value))
				{
					this._vchTipoPersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNombreEmpresa", DbType="VarChar(250)")]
		public string vchNombreEmpresa
		{
			get
			{
				return this._vchNombreEmpresa;
			}
			set
			{
				if ((this._vchNombreEmpresa != value))
				{
					this._vchNombreEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNombreCompleto", DbType="VarChar(250)")]
		public string vchNombreCompleto
		{
			get
			{
				return this._vchNombreCompleto;
			}
			set
			{
				if ((this._vchNombreCompleto != value))
				{
					this._vchNombreCompleto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchNombre", DbType="VarChar(100)")]
		public string vchNombre
		{
			get
			{
				return this._vchNombre;
			}
			set
			{
				if ((this._vchNombre != value))
				{
					this._vchNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchApPaterno", DbType="VarChar(100)")]
		public string vchApPaterno
		{
			get
			{
				return this._vchApPaterno;
			}
			set
			{
				if ((this._vchApPaterno != value))
				{
					this._vchApPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchApMaterno", DbType="VarChar(100)")]
		public string vchApMaterno
		{
			get
			{
				return this._vchApMaterno;
			}
			set
			{
				if ((this._vchApMaterno != value))
				{
					this._vchApMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFechaNacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> datFechaNacimiento
		{
			get
			{
				return this._datFechaNacimiento;
			}
			set
			{
				if ((this._datFechaNacimiento != value))
				{
					this._datFechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchLugarNacimiento", DbType="VarChar(100)")]
		public string vchLugarNacimiento
		{
			get
			{
				return this._vchLugarNacimiento;
			}
			set
			{
				if ((this._vchLugarNacimiento != value))
				{
					this._vchLugarNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchRFC", DbType="VarChar(13)")]
		public string vchRFC
		{
			get
			{
				return this._vchRFC;
			}
			set
			{
				if ((this._vchRFC != value))
				{
					this._vchRFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCURP", DbType="VarChar(18)")]
		public string vchCURP
		{
			get
			{
				return this._vchCURP;
			}
			set
			{
				if ((this._vchCURP != value))
				{
					this._vchCURP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintEdad", DbType="SmallInt")]
		public System.Nullable<short> sintEdad
		{
			get
			{
				return this._sintEdad;
			}
			set
			{
				if ((this._sintEdad != value))
				{
					this._sintEdad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTelefono", DbType="VarChar(10)")]
		public string vchTelefono
		{
			get
			{
				return this._vchTelefono;
			}
			set
			{
				if ((this._vchTelefono != value))
				{
					this._vchTelefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTelefonoMovil", DbType="VarChar(12)")]
		public string vchTelefonoMovil
		{
			get
			{
				return this._vchTelefonoMovil;
			}
			set
			{
				if ((this._vchTelefonoMovil != value))
				{
					this._vchTelefonoMovil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMail", DbType="VarChar(250)")]
		public string vchMail
		{
			get
			{
				return this._vchMail;
			}
			set
			{
				if ((this._vchMail != value))
				{
					this._vchMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitCausaRetencion", DbType="Bit")]
		public System.Nullable<bool> bitCausaRetencion
		{
			get
			{
				return this._bitCausaRetencion;
			}
			set
			{
				if ((this._bitCausaRetencion != value))
				{
					this._bitCausaRetencion = value;
				}
			}
		}
	}
	
	public partial class stp_ListarRelPersonaDireccionEmpresaResult
	{
		
		private int _intPersonaDomEmpreID;
		
		private string _vchPersona;
		
		private string _vchDomicilio;
		
		private string _vchEmpresa;
		
		private System.Nullable<bool> _bitActivo;
		
		public stp_ListarRelPersonaDireccionEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intPersonaDomEmpreID", DbType="Int NOT NULL")]
		public int intPersonaDomEmpreID
		{
			get
			{
				return this._intPersonaDomEmpreID;
			}
			set
			{
				if ((this._intPersonaDomEmpreID != value))
				{
					this._intPersonaDomEmpreID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchPersona", DbType="VarChar(250)")]
		public string vchPersona
		{
			get
			{
				return this._vchPersona;
			}
			set
			{
				if ((this._vchPersona != value))
				{
					this._vchPersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDomicilio", DbType="VarChar(275)")]
		public string vchDomicilio
		{
			get
			{
				return this._vchDomicilio;
			}
			set
			{
				if ((this._vchDomicilio != value))
				{
					this._vchDomicilio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchEmpresa", DbType="VarChar(250)")]
		public string vchEmpresa
		{
			get
			{
				return this._vchEmpresa;
			}
			set
			{
				if ((this._vchEmpresa != value))
				{
					this._vchEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
	
	public partial class stp_setPersonaResult
	{
		
		private string _vchResultado;
		
		private string _vchDescripcion;
		
		public stp_setPersonaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchResultado", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string vchResultado
		{
			get
			{
				return this._vchResultado;
			}
			set
			{
				if ((this._vchResultado != value))
				{
					this._vchResultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(46) NOT NULL", CanBeNull=false)]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
	
	public partial class stp_setRelaciónPersonaDomicilioEmpresaResult
	{
		
		private string _vchResultado;
		
		private string _vchDescripcion;
		
		public stp_setRelaciónPersonaDomicilioEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchResultado", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string vchResultado
		{
			get
			{
				return this._vchResultado;
			}
			set
			{
				if ((this._vchResultado != value))
				{
					this._vchResultado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescripcion", DbType="VarChar(61) NOT NULL", CanBeNull=false)]
		public string vchDescripcion
		{
			get
			{
				return this._vchDescripcion;
			}
			set
			{
				if ((this._vchDescripcion != value))
				{
					this._vchDescripcion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
