<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="PisoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="" Member="entSeleccionPiso">
    <Type Name="entSeleccionPiso" Id="ID1">
      <Column Name="sintPisoID" Type="System.Int16" CanBeNull="false" />
      <Column Name="decLongitud" Type="System.Decimal" CanBeNull="false" />
      <Column Name="vchMaterial" Type="System.String" CanBeNull="false" />
      <Column Name="decPesoUnitario" Storage="_decPesoPartida" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decPrecioUnitario" Storage="_decPrecioFinal" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decPesoBase" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decPrecioBase" Type="System.Decimal" CanBeNull="false" />
      <Column Name="sintTipoPisoID" Type="System.Int16" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.fn_getNumeroPiso" Method="fn_getNumeroPiso" IsComposable="true">
    <Parameter Name="intDatoPisoID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.stp_setSeleccionPiso" Method="stp_setSeleccionPiso">
    <Parameter Name="intSeleccionPisoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatoPisoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintTipoPisoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decLongitud" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPrecioTotal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPesoUnitario" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setSeleccionPisoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(56) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosSeleccionPiso" Method="stp_ListarDatosSeleccionPiso">
    <Parameter Name="intDatoPisoID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosSeleccionPisoResult">
      <Column Name="intSeleccionPisoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intDatoPisoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintTipoPisoID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPrecioTotal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPesoUnitario" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="vchMaterial" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosPiso" Method="stp_ListarDatosPiso">
    <Parameter Name="intDatoPisoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosPisoResult">
      <Column Name="intDatoPisoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decLargoPiso" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="bitUsoPatin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decAncho" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="bitTipoPisoAbierto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="decPesoUnitario" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decPrecioTotal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="bitGalvanizado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarPisoDriveIn" Method="stp_ListarPisoDriveIn">
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="decLargo" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="bitGalvanizado" Type="System.Boolean" DbType="Bit" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>