#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adsisplus.Cotyrsa.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbTyrsa")]
	public partial class PosteDriveInDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public PosteDriveInDataContext() : 
				base(global::Adsisplus.Cotyrsa.DataAccess.Properties.Settings.Default.dbTyrsaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PosteDriveInDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosteDriveInDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosteDriveInDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosteDriveInDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarPrecioPosteTC2")]
		public ISingleResult<stp_ListarPrecioPosteTC2Result> stp_ListarPrecioPosteTC2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intAlturaMarcoID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,4)")] System.Nullable<decimal> decFondoMarco)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intAlturaMarcoID, decFondoMarco);
			return ((ISingleResult<stp_ListarPrecioPosteTC2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarDatosPosteDriveIn")]
		public ISingleResult<stp_ListarDatosPosteDriveInResult> stp_ListarDatosPosteDriveIn([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatoPosteDriveInID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatoMarcoID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intDatoPosteDriveInID, intCotizacionID, intDatoMarcoID);
			return ((ISingleResult<stp_ListarDatosPosteDriveInResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarDatosMarcoDriveIn")]
		public ISingleResult<stp_ListarDatosMarcoDriveInResult> stp_ListarDatosMarcoDriveIn([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatoMarcoID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCotizacionID, intDatoMarcoID);
			return ((ISingleResult<stp_ListarDatosMarcoDriveInResult>)(result.ReturnValue));
		}
	}
	
	public partial class stp_ListarPrecioPosteTC2Result
	{
		
		private int _intConfiguraMarcoID;
		
		private System.Nullable<int> _intSKUID;
		
		private System.Nullable<decimal> _decCalibre;
		
		private System.Nullable<decimal> _decSolera;
		
		private System.Nullable<decimal> _decTotalKilo;
		
		private System.Nullable<decimal> _decPrecioTyrsa;
		
		private System.Nullable<decimal> _decRelacionPrecios;
		
		private System.Nullable<decimal> _decPrecioTyrsaMetro;
		
		private System.Nullable<decimal> _decPrecioTyrsaKg;
		
		private System.Nullable<short> _sintNumPosteReq;
		
		private System.Nullable<short> _sintNumTravesanio;
		
		public stp_ListarPrecioPosteTC2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intConfiguraMarcoID", DbType="Int NOT NULL")]
		public int intConfiguraMarcoID
		{
			get
			{
				return this._intConfiguraMarcoID;
			}
			set
			{
				if ((this._intConfiguraMarcoID != value))
				{
					this._intConfiguraMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSKUID", DbType="Int")]
		public System.Nullable<int> intSKUID
		{
			get
			{
				return this._intSKUID;
			}
			set
			{
				if ((this._intSKUID != value))
				{
					this._intSKUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCalibre", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> decCalibre
		{
			get
			{
				return this._decCalibre;
			}
			set
			{
				if ((this._decCalibre != value))
				{
					this._decCalibre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decSolera", DbType="Decimal(10,6)")]
		public System.Nullable<decimal> decSolera
		{
			get
			{
				return this._decSolera;
			}
			set
			{
				if ((this._decSolera != value))
				{
					this._decSolera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decTotalKilo", DbType="Decimal(8,4)")]
		public System.Nullable<decimal> decTotalKilo
		{
			get
			{
				return this._decTotalKilo;
			}
			set
			{
				if ((this._decTotalKilo != value))
				{
					this._decTotalKilo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsa", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decPrecioTyrsa
		{
			get
			{
				return this._decPrecioTyrsa;
			}
			set
			{
				if ((this._decPrecioTyrsa != value))
				{
					this._decPrecioTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decRelacionPrecios", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decRelacionPrecios
		{
			get
			{
				return this._decRelacionPrecios;
			}
			set
			{
				if ((this._decRelacionPrecios != value))
				{
					this._decRelacionPrecios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsaMetro", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decPrecioTyrsaMetro
		{
			get
			{
				return this._decPrecioTyrsaMetro;
			}
			set
			{
				if ((this._decPrecioTyrsaMetro != value))
				{
					this._decPrecioTyrsaMetro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsaKg", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decPrecioTyrsaKg
		{
			get
			{
				return this._decPrecioTyrsaKg;
			}
			set
			{
				if ((this._decPrecioTyrsaKg != value))
				{
					this._decPrecioTyrsaKg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintNumPosteReq", DbType="SmallInt")]
		public System.Nullable<short> sintNumPosteReq
		{
			get
			{
				return this._sintNumPosteReq;
			}
			set
			{
				if ((this._sintNumPosteReq != value))
				{
					this._sintNumPosteReq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintNumTravesanio", DbType="SmallInt")]
		public System.Nullable<short> sintNumTravesanio
		{
			get
			{
				return this._sintNumTravesanio;
			}
			set
			{
				if ((this._sintNumTravesanio != value))
				{
					this._sintNumTravesanio = value;
				}
			}
		}
	}
	
	public partial class stp_ListarDatosPosteDriveInResult
	{
		
		private int _intDatoPosteDriveInID;
		
		private System.Nullable<int> _intElementoID;
		
		private System.Nullable<int> _intCotizacionID;
		
		private System.Nullable<int> _intDetCotizaID;
		
		private System.Nullable<int> _intDatoMarcoID;
		
		private System.Nullable<int> _intSKUID;
		
		private System.Nullable<int> _intCantidad;
		
		private System.Nullable<decimal> _decCalibre;
		
		private System.Nullable<decimal> _decSolera;
		
		private System.Nullable<decimal> _decTotalKilo;
		
		private System.Nullable<decimal> _decPrecioTyrsa;
		
		private System.Nullable<decimal> _decRelacionPrecios;
		
		private System.Nullable<decimal> _decPrecioTyrsaMetro;
		
		private System.Nullable<decimal> _decPrecioTyrsaKg;
		
		private System.Nullable<short> _sintNumPosteReq;
		
		private System.Nullable<short> _sintNumTravesanio;
		
		private System.Nullable<decimal> _decPrecioVentaTotal;
		
		private System.Nullable<decimal> _decPesoTotal;
		
		private System.Nullable<int> _intAlturaMarcoID;
		
		private int _intSeleccionMarcoID;
		
		private System.Nullable<int> _intDetCotizaID_Marco;
		
		private System.Nullable<decimal> _decFondo;
		
		private System.Nullable<bool> _bitActivo;
		
		public stp_ListarDatosPosteDriveInResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDatoPosteDriveInID", DbType="Int NOT NULL")]
		public int intDatoPosteDriveInID
		{
			get
			{
				return this._intDatoPosteDriveInID;
			}
			set
			{
				if ((this._intDatoPosteDriveInID != value))
				{
					this._intDatoPosteDriveInID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intElementoID", DbType="Int")]
		public System.Nullable<int> intElementoID
		{
			get
			{
				return this._intElementoID;
			}
			set
			{
				if ((this._intElementoID != value))
				{
					this._intElementoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCotizacionID", DbType="Int")]
		public System.Nullable<int> intCotizacionID
		{
			get
			{
				return this._intCotizacionID;
			}
			set
			{
				if ((this._intCotizacionID != value))
				{
					this._intCotizacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDetCotizaID", DbType="Int")]
		public System.Nullable<int> intDetCotizaID
		{
			get
			{
				return this._intDetCotizaID;
			}
			set
			{
				if ((this._intDetCotizaID != value))
				{
					this._intDetCotizaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDatoMarcoID", DbType="Int")]
		public System.Nullable<int> intDatoMarcoID
		{
			get
			{
				return this._intDatoMarcoID;
			}
			set
			{
				if ((this._intDatoMarcoID != value))
				{
					this._intDatoMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSKUID", DbType="Int")]
		public System.Nullable<int> intSKUID
		{
			get
			{
				return this._intSKUID;
			}
			set
			{
				if ((this._intSKUID != value))
				{
					this._intSKUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidad", DbType="Int")]
		public System.Nullable<int> intCantidad
		{
			get
			{
				return this._intCantidad;
			}
			set
			{
				if ((this._intCantidad != value))
				{
					this._intCantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCalibre", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decCalibre
		{
			get
			{
				return this._decCalibre;
			}
			set
			{
				if ((this._decCalibre != value))
				{
					this._decCalibre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decSolera", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decSolera
		{
			get
			{
				return this._decSolera;
			}
			set
			{
				if ((this._decSolera != value))
				{
					this._decSolera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decTotalKilo", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decTotalKilo
		{
			get
			{
				return this._decTotalKilo;
			}
			set
			{
				if ((this._decTotalKilo != value))
				{
					this._decTotalKilo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsa", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decPrecioTyrsa
		{
			get
			{
				return this._decPrecioTyrsa;
			}
			set
			{
				if ((this._decPrecioTyrsa != value))
				{
					this._decPrecioTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decRelacionPrecios", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decRelacionPrecios
		{
			get
			{
				return this._decRelacionPrecios;
			}
			set
			{
				if ((this._decRelacionPrecios != value))
				{
					this._decRelacionPrecios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsaMetro", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decPrecioTyrsaMetro
		{
			get
			{
				return this._decPrecioTyrsaMetro;
			}
			set
			{
				if ((this._decPrecioTyrsaMetro != value))
				{
					this._decPrecioTyrsaMetro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsaKg", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> decPrecioTyrsaKg
		{
			get
			{
				return this._decPrecioTyrsaKg;
			}
			set
			{
				if ((this._decPrecioTyrsaKg != value))
				{
					this._decPrecioTyrsaKg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintNumPosteReq", DbType="SmallInt")]
		public System.Nullable<short> sintNumPosteReq
		{
			get
			{
				return this._sintNumPosteReq;
			}
			set
			{
				if ((this._sintNumPosteReq != value))
				{
					this._sintNumPosteReq = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintNumTravesanio", DbType="SmallInt")]
		public System.Nullable<short> sintNumTravesanio
		{
			get
			{
				return this._sintNumTravesanio;
			}
			set
			{
				if ((this._sintNumTravesanio != value))
				{
					this._sintNumTravesanio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioVentaTotal", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decPrecioVentaTotal
		{
			get
			{
				return this._decPrecioVentaTotal;
			}
			set
			{
				if ((this._decPrecioVentaTotal != value))
				{
					this._decPrecioVentaTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPesoTotal", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decPesoTotal
		{
			get
			{
				return this._decPesoTotal;
			}
			set
			{
				if ((this._decPesoTotal != value))
				{
					this._decPesoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAlturaMarcoID", DbType="Int")]
		public System.Nullable<int> intAlturaMarcoID
		{
			get
			{
				return this._intAlturaMarcoID;
			}
			set
			{
				if ((this._intAlturaMarcoID != value))
				{
					this._intAlturaMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSeleccionMarcoID", DbType="Int NOT NULL")]
		public int intSeleccionMarcoID
		{
			get
			{
				return this._intSeleccionMarcoID;
			}
			set
			{
				if ((this._intSeleccionMarcoID != value))
				{
					this._intSeleccionMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDetCotizaID_Marco", DbType="Int")]
		public System.Nullable<int> intDetCotizaID_Marco
		{
			get
			{
				return this._intDetCotizaID_Marco;
			}
			set
			{
				if ((this._intDetCotizaID_Marco != value))
				{
					this._intDetCotizaID_Marco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decFondo", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decFondo
		{
			get
			{
				return this._decFondo;
			}
			set
			{
				if ((this._decFondo != value))
				{
					this._decFondo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
	
	public partial class stp_ListarDatosMarcoDriveInResult
	{
		
		private System.Nullable<int> _intDetCotizaID;
		
		private int _intSeleccionMarcoID;
		
		private System.Nullable<int> _intNumeroNiveles;
		
		private System.Nullable<bool> _bitRolado;
		
		private System.Nullable<bool> _bitEstructural;
		
		private System.Nullable<decimal> _decFondoMarco;
		
		private System.Nullable<decimal> _decAlturaMarco;
		
		private System.Nullable<decimal> _decAlturaPandeoRack;
		
		private System.Nullable<decimal> _decCapacidadCargaTotal;
		
		private string _SKU;
		
		private System.Nullable<decimal> _decPesoMarco;
		
		private System.Nullable<decimal> _decPrecioUnitario;
		
		private System.Nullable<int> _intTipoID;
		
		private System.Nullable<int> _intMaterialID;
		
		private System.Nullable<decimal> _decFondo;
		
		private System.Nullable<decimal> _decAltura;
		
		private System.Nullable<decimal> _decAlturaPandeo;
		
		private System.Nullable<decimal> _decCapacidadMarco;
		
		private int _intDatoMarcoID;
		
		private System.Nullable<short> _sintPinturaID;
		
		private System.Nullable<short> _sintCantidad;
		
		private System.Nullable<decimal> _decMedidaAlto;
		
		private System.Nullable<decimal> _decAlturaPandeo1;
		
		private System.Nullable<decimal> _decAltura1;
		
		private System.Nullable<decimal> _decFondo1;
		
		public stp_ListarDatosMarcoDriveInResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDetCotizaID", DbType="Int")]
		public System.Nullable<int> intDetCotizaID
		{
			get
			{
				return this._intDetCotizaID;
			}
			set
			{
				if ((this._intDetCotizaID != value))
				{
					this._intDetCotizaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSeleccionMarcoID", DbType="Int NOT NULL")]
		public int intSeleccionMarcoID
		{
			get
			{
				return this._intSeleccionMarcoID;
			}
			set
			{
				if ((this._intSeleccionMarcoID != value))
				{
					this._intSeleccionMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intNumeroNiveles", DbType="Int")]
		public System.Nullable<int> intNumeroNiveles
		{
			get
			{
				return this._intNumeroNiveles;
			}
			set
			{
				if ((this._intNumeroNiveles != value))
				{
					this._intNumeroNiveles = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitRolado", DbType="Bit")]
		public System.Nullable<bool> bitRolado
		{
			get
			{
				return this._bitRolado;
			}
			set
			{
				if ((this._bitRolado != value))
				{
					this._bitRolado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitEstructural", DbType="Bit")]
		public System.Nullable<bool> bitEstructural
		{
			get
			{
				return this._bitEstructural;
			}
			set
			{
				if ((this._bitEstructural != value))
				{
					this._bitEstructural = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decFondoMarco", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decFondoMarco
		{
			get
			{
				return this._decFondoMarco;
			}
			set
			{
				if ((this._decFondoMarco != value))
				{
					this._decFondoMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaMarco", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAlturaMarco
		{
			get
			{
				return this._decAlturaMarco;
			}
			set
			{
				if ((this._decAlturaMarco != value))
				{
					this._decAlturaMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPandeoRack", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAlturaPandeoRack
		{
			get
			{
				return this._decAlturaPandeoRack;
			}
			set
			{
				if ((this._decAlturaPandeoRack != value))
				{
					this._decAlturaPandeoRack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCapacidadCargaTotal", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> decCapacidadCargaTotal
		{
			get
			{
				return this._decCapacidadCargaTotal;
			}
			set
			{
				if ((this._decCapacidadCargaTotal != value))
				{
					this._decCapacidadCargaTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SKU", DbType="VarChar(50)")]
		public string SKU
		{
			get
			{
				return this._SKU;
			}
			set
			{
				if ((this._SKU != value))
				{
					this._SKU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPesoMarco", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decPesoMarco
		{
			get
			{
				return this._decPesoMarco;
			}
			set
			{
				if ((this._decPesoMarco != value))
				{
					this._decPesoMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioUnitario", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> decPrecioUnitario
		{
			get
			{
				return this._decPrecioUnitario;
			}
			set
			{
				if ((this._decPrecioUnitario != value))
				{
					this._decPrecioUnitario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoID", DbType="Int")]
		public System.Nullable<int> intTipoID
		{
			get
			{
				return this._intTipoID;
			}
			set
			{
				if ((this._intTipoID != value))
				{
					this._intTipoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intMaterialID", DbType="Int")]
		public System.Nullable<int> intMaterialID
		{
			get
			{
				return this._intMaterialID;
			}
			set
			{
				if ((this._intMaterialID != value))
				{
					this._intMaterialID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decFondo", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decFondo
		{
			get
			{
				return this._decFondo;
			}
			set
			{
				if ((this._decFondo != value))
				{
					this._decFondo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAltura", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAltura
		{
			get
			{
				return this._decAltura;
			}
			set
			{
				if ((this._decAltura != value))
				{
					this._decAltura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPandeo", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAlturaPandeo
		{
			get
			{
				return this._decAlturaPandeo;
			}
			set
			{
				if ((this._decAlturaPandeo != value))
				{
					this._decAlturaPandeo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCapacidadMarco", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decCapacidadMarco
		{
			get
			{
				return this._decCapacidadMarco;
			}
			set
			{
				if ((this._decCapacidadMarco != value))
				{
					this._decCapacidadMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDatoMarcoID", DbType="Int NOT NULL")]
		public int intDatoMarcoID
		{
			get
			{
				return this._intDatoMarcoID;
			}
			set
			{
				if ((this._intDatoMarcoID != value))
				{
					this._intDatoMarcoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintPinturaID", DbType="SmallInt")]
		public System.Nullable<short> sintPinturaID
		{
			get
			{
				return this._sintPinturaID;
			}
			set
			{
				if ((this._sintPinturaID != value))
				{
					this._sintPinturaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sintCantidad", DbType="SmallInt")]
		public System.Nullable<short> sintCantidad
		{
			get
			{
				return this._sintCantidad;
			}
			set
			{
				if ((this._sintCantidad != value))
				{
					this._sintCantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decMedidaAlto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> decMedidaAlto
		{
			get
			{
				return this._decMedidaAlto;
			}
			set
			{
				if ((this._decMedidaAlto != value))
				{
					this._decMedidaAlto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAlturaPandeo1", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAlturaPandeo1
		{
			get
			{
				return this._decAlturaPandeo1;
			}
			set
			{
				if ((this._decAlturaPandeo1 != value))
				{
					this._decAlturaPandeo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decAltura1", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decAltura1
		{
			get
			{
				return this._decAltura1;
			}
			set
			{
				if ((this._decAltura1 != value))
				{
					this._decAltura1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decFondo1", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decFondo1
		{
			get
			{
				return this._decFondo1;
			}
			set
			{
				if ((this._decFondo1 != value))
				{
					this._decFondo1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
