<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="PosteDriveInDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_ListarPrecioPosteTC2" Method="stp_ListarPrecioPosteTC2">
    <Parameter Name="intAlturaMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decFondoMarco" Type="System.Decimal" DbType="Decimal(18,4)" />
    <ElementType Name="stp_ListarPrecioPosteTC2Result">
      <Column Name="intConfiguraMarcoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intSKUID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decCalibre" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="decSolera" Type="System.Decimal" DbType="Decimal(10,6)" CanBeNull="true" />
      <Column Name="decTotalKilo" Type="System.Decimal" DbType="Decimal(8,4)" CanBeNull="true" />
      <Column Name="decPrecioTyrsa" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decRelacionPrecios" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decPrecioTyrsaMetro" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decPrecioTyrsaKg" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="sintNumPosteReq" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sintNumTravesanio" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosPosteDriveIn" Method="stp_ListarDatosPosteDriveIn">
    <Parameter Name="intDatoPosteDriveInID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosPosteDriveInResult">
      <Column Name="intDatoPosteDriveInID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intSKUID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decCalibre" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decSolera" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decTotalKilo" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decPrecioTyrsa" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decRelacionPrecios" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decPrecioTyrsaMetro" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decPrecioTyrsaKg" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="sintNumPosteReq" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="sintNumTravesanio" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intDatosDriveInID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitDobleMonten" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="decAlturaDobleMonten" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intAlturaMarcoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decFondo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>