<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="ProtectoresDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_ListarDatosProtectorBateria" Method="stp_ListarDatosProtectorBateria">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosProtectorBateriaResult">
      <Column Name="intProtectorBateriaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchFolio" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intCantidadSencilla" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCantidadDoble" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCantidadTriple" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCantidadCuadruple" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decPrecioSencilla" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="decPrecioDoble" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="decPrecioTriple" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="decPrecioCuadruple" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="decLargoSencilla" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decLargoDoble" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decLargoTriple" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarSeleccionProtectorRack" Method="stp_ListarSeleccionProtectorRack">
    <ElementType Name="stp_ListarSeleccionProtectorRackResult">
      <Column Name="vchTipoProtector" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="decPrecioFinal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarSeleccionBateriaSencilla" Method="stp_ListarSeleccionBateriaSencilla">
    <ElementType Name="stp_ListarSeleccionBateriaSencillaResult">
      <Column Name="SKU" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="intNumBotas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intNumBarras" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
      <Column Name="intAltura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarSeleccionBateriaDoble" Method="stp_ListarSeleccionBateriaDoble">
    <ElementType Name="stp_ListarSeleccionBateriaDobleResult">
      <Column Name="SKU" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="intNumBotas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intNumBarras" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchMaterial" Type="System.String" DbType="VarChar(17) NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
      <Column Name="intAltura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarSeleccionBateriaCuadruple" Method="stp_ListarSeleccionBateriaCuadruple">
    <ElementType Name="stp_ListarSeleccionBateriaCuadrupleResult">
      <Column Name="SKU" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="intNumBotas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intNumBarras" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchMaterial" Type="System.String" DbType="VarChar(17) NOT NULL" CanBeNull="false" />
      <Column Name="TOTAL" Type="System.Decimal" DbType="Decimal(38,3)" CanBeNull="true" />
      <Column Name="intAltura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosProtectorPoste" Method="stp_ListarDatosProtectorPoste">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosProtectorPosteResult">
      <Column Name="intProtectorPosteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchFolio" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchPintura" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intCantidadProtectorPoste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="sintLongitudID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="decPrecioVentaTotal" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decPrecioVentaUnitario" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>