<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="SistemaDriveInDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.stp_ListarMstDiveIn" Method="stp_ListarMstDiveIn">
    <Parameter Name="sintTipoVigaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="sintLongitudID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCalibreID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintLargoID" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="stp_ListarMstDiveInResult">
      <Column Name="intCapacidadVigaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchTipoViga" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="vchLongitud" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="vchCalibre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="intLargo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decCargaKg" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decCargaLbs" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decCoeficienteSeguridad" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="datFechaAlta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosBrazo" Method="stp_setDatosBrazo">
    <Parameter Name="intBrazoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="sintLargoBrazoID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decLargo" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decPrecioVentaUnitario" Type="System.Decimal" DbType="Decimal(18,3)" />
    <Parameter Name="decPrecioVentaTotal" Type="System.Decimal" DbType="Decimal(18,3)" />
    <Parameter Name="decPesoUnitario" Type="System.Decimal" DbType="Decimal(20,3)" />
    <Parameter Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="intSeleccionBrazoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintDriveInID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decLongitud" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decAncho" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decTotalKiloUnitario" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decPrecioFinal" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosBrazoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(56) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosPiso" Method="stp_setDatosPiso">
    <Parameter Name="intDatoPisoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="decLargoPiso" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="bitUsoPatin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decAncho" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="bitTipoPisoAbierto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="decPesoUnitario" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPrecioTotal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="bitGalvanizado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosPisoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(44) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosRielTarima" Method="stp_setDatosRielTarima">
    <Parameter Name="intRielTarimaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintTipoRielTarimaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="decCarga" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decLargo" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="intSeleccionRielCargaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintDriveInID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decLongitud" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAncho" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decTotalKiloUnitario" Type="System.Decimal" DbType="Decimal(12,3)" />
    <Parameter Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPrecioFinal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPrecioVentaTotal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosRielTarimaResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(51) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosAtirantado" Method="stp_setDatosAtirantado">
    <Parameter Name="intAtirantadoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decLargo" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decLongitud" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="intCalibreID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intSeleccionArriestradoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintDriveInID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decAncho" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decTotalKiloUnitario" Type="System.Decimal" DbType="Decimal(12,3)" />
    <Parameter Name="decPrecioFinal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaTotal" Type="System.Decimal" DbType="Decimal(18,3)" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosAtirantadoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosGuiaEntrada" Method="stp_setDatosGuiaEntrada">
    <Parameter Name="intGuiaEntradaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decLargo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intSeleccionGuiaMontaCargaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="vchMedida" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="decTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decTotalKiloUnitario" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPrecioFinal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPrecioMasLargoTotal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosGuiaEntradaResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(52) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosBarandal" Method="stp_setDatosBarandal">
    <Parameter Name="intDatosBarandalID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decLargo" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decCantidad" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="decPrecioTotal" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="decPesoUnitario" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosBarandalResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(48) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosVigaAtirantado" Method="stp_setDatosVigaAtirantado">
    <Parameter Name="intVigaAtirantadoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decLargo" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decPrecioVentaUnitario" Type="System.Decimal" DbType="Decimal(18,3)" />
    <Parameter Name="decPrecioVentaTotal" Type="System.Decimal" DbType="Decimal(18,3)" />
    <Parameter Name="decPesoUnitario" Type="System.Decimal" DbType="Decimal(20,3)" />
    <Parameter Name="decPeso" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decLongitud" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="intCalibreID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintLongitudID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="bitVigaTipoCaja" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosVigaAtirantadoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(55) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosPosteDriveIn" Method="stp_setDatosPosteDriveIn">
    <Parameter Name="intDatoPosteDriveInID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatoMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intSKUID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="decCalibre" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decSolera" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decTotalKilo" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decPrecioTyrsa" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decRelacionPrecios" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decPrecioTyrsaMetro" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decPrecioTyrsaKg" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="sintNumPosteReq" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="sintNumTravesanio" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decPesoTotal" Type="System.Decimal" DbType="Decimal(12,3)" />
    <Parameter Name="decPrecioVentaTotal" Type="System.Decimal" DbType="Decimal(12,3)" />
    <Parameter Name="bitDobleMonten" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="decAlturaDobleMonten" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosPosteDriveInResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(54) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosDriveIn" Method="stp_setDatosDriveIn">
    <Parameter Name="intDatosDriveInID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitEsEstructural" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="bitDobleMonten" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="decFrente" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decFondo" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPeso" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decAnchoMonta" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decAlturaMaxima" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decAlturaCanastilla" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decCapacidadMaxima" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="sintMaterialDriveInID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decAlturaDobleMonten" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosDriveInResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(49) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosDriveIn" Method="stp_ListarDatosDriveIn">
    <Parameter Name="intDatosDriveInID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosDriveInResult">
      <Column Name="intDatosDriveInID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitEsEstructural" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bitDobleMonten" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="decFrente" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decFondo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decPeso" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="decAnchoMonta" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decAlturaMaxima" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decAlturaCanastilla" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decCapacidadMaxima" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="decAlturaDobleMonten" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="sintMaterialDriveInID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>