<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="SistemasTyrsaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="" Member="mstTornilleria">
    <Type Name="mstTornilleria" Id="ID1">
      <Column Name="intDatoTornilleriaID" Type="System.Int32" CanBeNull="false" />
      <Column Name="sintTornilleriaID" Type="System.Int16" CanBeNull="false" />
      <Column Name="intElementoID" Type="System.Int32" CanBeNull="false" />
      <Column Name="intCotizacionID" Type="System.Int32" CanBeNull="false" />
      <Column Name="intDetCotizaID" Type="System.Int32" CanBeNull="false" />
      <Column Name="vchSubMenu" Type="System.String" CanBeNull="false" />
      <Column Name="vchDescripcion" Type="System.String" CanBeNull="false" />
      <Column Name="intCantidad" Type="System.Int32" CanBeNull="false" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decTotal" Type="System.Decimal" CanBeNull="false" />
      <Column Name="bitActivo" Type="System.Boolean" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.stp_setDatosViga" Method="stp_setDatosViga">
    <Parameter Name="intDatosVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SKU" Parameter="sKU" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatoMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decLargo" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="intPiezaXLamina" Type="System.Int32" DbType="Int" />
    <Parameter Name="intPiezaXLaminaCuerpo" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosVigaResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(47) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosDistanciador" Method="stp_setDatosDistanciador">
    <Parameter Name="intDistanciadorID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCantidadDistanciador" Type="System.Int32" DbType="Int" />
    <Parameter Name="decLargoDistanciador" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosDistanciadorResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(55) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosPanel" Method="stp_setDatosPanel">
    <Parameter Name="intDatosPanelID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatoMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decAnchoPanel" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="intCantidadPanel" Type="System.Int32" DbType="Int" />
    <Parameter Name="decCapacidadCargaPanel" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosPanelResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(48) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosCrossBar" Method="stp_setDatosCrossBar">
    <Parameter Name="intDatosCrossBarID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatoMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decAnchoCrossBar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="bitConectorVigaCrossbar" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="intCantidadNivelCrossbar" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosCrossBarResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(52) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarTornillosSelectivo" Method="stp_ListarTornillosSelectivo">
    <Parameter Name="intConfiguraMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitEstructural" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="bitEsCuadruple" Type="System.Boolean" DbType="Bit" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.stp_ListarTornillosSelectivoCotizacion" Method="stp_ListarTornillosSelectivoCotizacion">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarTornillosSelectivoCotizacionResult">
      <Column Name="intDatoTornilleriaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sintTornilleriaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchSubMenu" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decTotal" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosParrilla" Method="stp_setDatosParrilla">
    <Parameter Name="intParrillaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decFrenteParrilla" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decFondoParrilla" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decCostoParrilla" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decTamanioCuadroParrilla" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="intCantidadParrilla" Type="System.Int32" DbType="Int" />
    <Parameter Name="decPesoParrilla" Type="System.Decimal" DbType="Decimal(8,5)" />
    <Parameter Name="bitGalvanizado" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="bitPintura" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="decPrecioVentaUnitario" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaTotal" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosParrillaResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(51) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosProtectorPoste" Method="stp_setDatosProtectorPoste">
    <Parameter Name="intProtectorPosteID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCantidadProtectorPoste" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="sintLongitudID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decPrecioVentaTotal" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaUnitario" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosProtectorPosteResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(58) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosVigaTope" Method="stp_setDatosVigaTope">
    <Parameter Name="intVigaTopeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatosVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaUnitario" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaTotal" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPeso" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="sintLongitudID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intCalibreID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decLargo" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosVigaTopeResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(52) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosProtectorBateria" Method="stp_setDatosProtectorBateria">
    <Parameter Name="intProtectorBateriaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCantidadSencilla" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCantidadDoble" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCantidadCuadruple" Type="System.Int32" DbType="Int" />
    <Parameter Name="decPrecioSencilla" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioDoble" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioCuadruple" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decLargoSencilla" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decLargoDoble" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decLargoCuadruple" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaUnitarioSencilla" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaUnitarioDoble" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaUnitarioCuadruple" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaTotaloSencilla" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaTotalDoble" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioVentaTotalCuadruple" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAlturaSencilla" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAlturaDoble" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAlturaCuadruple" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="sintPinturaIDSencilla" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="sintPinturaIDDoble" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="sintPinturaIDCuadruple" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intBotasSencilla" Type="System.Int32" DbType="Int" />
    <Parameter Name="intBotasDoble" Type="System.Int32" DbType="Int" />
    <Parameter Name="intBotasCuadruple" Type="System.Int32" DbType="Int" />
    <Parameter Name="intBarrasSencilla" Type="System.Int32" DbType="Int" />
    <Parameter Name="intBarrasDoble" Type="System.Int32" DbType="Int" />
    <Parameter Name="intBarrasCuadruple" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosProtectorBateriaResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setDatosMarco" Method="stp_setDatosMarco">
    <Parameter Name="intDatoMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="sintCantidad" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="decAlturaPandeo" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decFondo" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setDatosMarcoResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(48) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>