#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adsisplus.Cotyrsa.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbTyrsa")]
	public partial class SistemasTyrsaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public SistemasTyrsaDataContext() : 
				base(global::Adsisplus.Cotyrsa.DataAccess.Properties.Settings.Default.dbTyrsaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SistemasTyrsaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemasTyrsaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemasTyrsaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemasTyrsaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.stp_ListarRelSistemaSelectivo")]
		public ISingleResult<stp_ListarRelSistemaSelectivoResult> stp_ListarRelSistemaSelectivo(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intCotizacionID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoElementoCoti_Producto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoElementoID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intTipoElementoAlmacenID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intConfiguraMarcoID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intConfiguraVigaID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatoMarcoID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatosVigaID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatosPanelID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDatosCrossBarID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intDistanciadorID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intParrillaID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intVigaTopeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intProtectorPosteID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> intProtectorBateriaID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> sintSistemaCargaMarcoID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> datFechaAlta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), intCotizacionID, intTipoElementoCoti_Producto, intTipoElementoID, intTipoElementoAlmacenID, intConfiguraMarcoID, intConfiguraVigaID, intDatoMarcoID, intDatosVigaID, intDatosPanelID, intDatosCrossBarID, intDistanciadorID, intParrillaID, intVigaTopeID, intProtectorPosteID, intProtectorBateriaID, sintSistemaCargaMarcoID, datFechaAlta);
			return ((ISingleResult<stp_ListarRelSistemaSelectivoResult>)(result.ReturnValue));
		}
	}
	
	public partial class stp_ListarRelSistemaSelectivoResult
	{
		
		private int _intTipoElementoCoti_Producto;
		
		private System.Nullable<int> _intCotizacionID;
		
		private string _vchDescElementoCotizar;
		
		private string _vchProductoAcero;
		
		private System.Nullable<decimal> _decPrecioTyrsa;
		
		private string _vchConfiguraViga;
		
		private System.Nullable<short> _intCantidadMarco;
		
		private System.Nullable<int> _intCantidadViga;
		
		private System.Nullable<int> _intCantidadPanel;
		
		private System.Nullable<int> _intCantidadNivelCrossbar;
		
		private System.Nullable<int> _intCantidadDistanciador;
		
		private System.Nullable<decimal> _decCostoParrilla;
		
		private System.Nullable<int> _intCantidadVigaTope;
		
		private System.Nullable<int> _intCantidadProctorPoste;
		
		private System.Nullable<int> _intCantidadSencillaProtectorBateria;
		
		private System.Nullable<int> _intCantidadDobleProtectorBateria;
		
		private System.Nullable<int> _intCantidadCuadrupleProtectorBateria;
		
		private string _vchFondoTyrsaMarco;
		
		private string _vchFrenteTyrsaMarco;
		
		private System.Nullable<int> _intCapacidadPesoMarco;
		
		private string _vchFondoTyrsaPoste;
		
		private string _vchFrenteTyrsaPoste;
		
		private System.Nullable<int> _intCapacidadPesoPoste;
		
		private System.Nullable<System.DateTime> _datFechaAlta;
		
		private System.Nullable<bool> _bitActivo;
		
		public stp_ListarRelSistemaSelectivoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intTipoElementoCoti_Producto", DbType="Int NOT NULL")]
		public int intTipoElementoCoti_Producto
		{
			get
			{
				return this._intTipoElementoCoti_Producto;
			}
			set
			{
				if ((this._intTipoElementoCoti_Producto != value))
				{
					this._intTipoElementoCoti_Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCotizacionID", DbType="Int")]
		public System.Nullable<int> intCotizacionID
		{
			get
			{
				return this._intCotizacionID;
			}
			set
			{
				if ((this._intCotizacionID != value))
				{
					this._intCotizacionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchDescElementoCotizar", DbType="VarChar(25)")]
		public string vchDescElementoCotizar
		{
			get
			{
				return this._vchDescElementoCotizar;
			}
			set
			{
				if ((this._vchDescElementoCotizar != value))
				{
					this._vchDescElementoCotizar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductoAcero", DbType="VarChar(25)")]
		public string vchProductoAcero
		{
			get
			{
				return this._vchProductoAcero;
			}
			set
			{
				if ((this._vchProductoAcero != value))
				{
					this._vchProductoAcero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decPrecioTyrsa", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> decPrecioTyrsa
		{
			get
			{
				return this._decPrecioTyrsa;
			}
			set
			{
				if ((this._decPrecioTyrsa != value))
				{
					this._decPrecioTyrsa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchConfiguraViga", DbType="VarChar(250)")]
		public string vchConfiguraViga
		{
			get
			{
				return this._vchConfiguraViga;
			}
			set
			{
				if ((this._vchConfiguraViga != value))
				{
					this._vchConfiguraViga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadMarco", DbType="SmallInt")]
		public System.Nullable<short> intCantidadMarco
		{
			get
			{
				return this._intCantidadMarco;
			}
			set
			{
				if ((this._intCantidadMarco != value))
				{
					this._intCantidadMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadViga", DbType="Int")]
		public System.Nullable<int> intCantidadViga
		{
			get
			{
				return this._intCantidadViga;
			}
			set
			{
				if ((this._intCantidadViga != value))
				{
					this._intCantidadViga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadPanel", DbType="Int")]
		public System.Nullable<int> intCantidadPanel
		{
			get
			{
				return this._intCantidadPanel;
			}
			set
			{
				if ((this._intCantidadPanel != value))
				{
					this._intCantidadPanel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadNivelCrossbar", DbType="Int")]
		public System.Nullable<int> intCantidadNivelCrossbar
		{
			get
			{
				return this._intCantidadNivelCrossbar;
			}
			set
			{
				if ((this._intCantidadNivelCrossbar != value))
				{
					this._intCantidadNivelCrossbar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadDistanciador", DbType="Int")]
		public System.Nullable<int> intCantidadDistanciador
		{
			get
			{
				return this._intCantidadDistanciador;
			}
			set
			{
				if ((this._intCantidadDistanciador != value))
				{
					this._intCantidadDistanciador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_decCostoParrilla", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> decCostoParrilla
		{
			get
			{
				return this._decCostoParrilla;
			}
			set
			{
				if ((this._decCostoParrilla != value))
				{
					this._decCostoParrilla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadVigaTope", DbType="Int")]
		public System.Nullable<int> intCantidadVigaTope
		{
			get
			{
				return this._intCantidadVigaTope;
			}
			set
			{
				if ((this._intCantidadVigaTope != value))
				{
					this._intCantidadVigaTope = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadProctorPoste", DbType="Int")]
		public System.Nullable<int> intCantidadProctorPoste
		{
			get
			{
				return this._intCantidadProctorPoste;
			}
			set
			{
				if ((this._intCantidadProctorPoste != value))
				{
					this._intCantidadProctorPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadSencillaProtectorBateria", DbType="Int")]
		public System.Nullable<int> intCantidadSencillaProtectorBateria
		{
			get
			{
				return this._intCantidadSencillaProtectorBateria;
			}
			set
			{
				if ((this._intCantidadSencillaProtectorBateria != value))
				{
					this._intCantidadSencillaProtectorBateria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadDobleProtectorBateria", DbType="Int")]
		public System.Nullable<int> intCantidadDobleProtectorBateria
		{
			get
			{
				return this._intCantidadDobleProtectorBateria;
			}
			set
			{
				if ((this._intCantidadDobleProtectorBateria != value))
				{
					this._intCantidadDobleProtectorBateria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCantidadCuadrupleProtectorBateria", DbType="Int")]
		public System.Nullable<int> intCantidadCuadrupleProtectorBateria
		{
			get
			{
				return this._intCantidadCuadrupleProtectorBateria;
			}
			set
			{
				if ((this._intCantidadCuadrupleProtectorBateria != value))
				{
					this._intCantidadCuadrupleProtectorBateria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoTyrsaMarco", DbType="VarChar(25)")]
		public string vchFondoTyrsaMarco
		{
			get
			{
				return this._vchFondoTyrsaMarco;
			}
			set
			{
				if ((this._vchFondoTyrsaMarco != value))
				{
					this._vchFondoTyrsaMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFrenteTyrsaMarco", DbType="VarChar(25)")]
		public string vchFrenteTyrsaMarco
		{
			get
			{
				return this._vchFrenteTyrsaMarco;
			}
			set
			{
				if ((this._vchFrenteTyrsaMarco != value))
				{
					this._vchFrenteTyrsaMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCapacidadPesoMarco", DbType="Int")]
		public System.Nullable<int> intCapacidadPesoMarco
		{
			get
			{
				return this._intCapacidadPesoMarco;
			}
			set
			{
				if ((this._intCapacidadPesoMarco != value))
				{
					this._intCapacidadPesoMarco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFondoTyrsaPoste", DbType="VarChar(25)")]
		public string vchFondoTyrsaPoste
		{
			get
			{
				return this._vchFondoTyrsaPoste;
			}
			set
			{
				if ((this._vchFondoTyrsaPoste != value))
				{
					this._vchFondoTyrsaPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFrenteTyrsaPoste", DbType="VarChar(25)")]
		public string vchFrenteTyrsaPoste
		{
			get
			{
				return this._vchFrenteTyrsaPoste;
			}
			set
			{
				if ((this._vchFrenteTyrsaPoste != value))
				{
					this._vchFrenteTyrsaPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCapacidadPesoPoste", DbType="Int")]
		public System.Nullable<int> intCapacidadPesoPoste
		{
			get
			{
				return this._intCapacidadPesoPoste;
			}
			set
			{
				if ((this._intCapacidadPesoPoste != value))
				{
					this._intCapacidadPesoPoste = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datFechaAlta", DbType="Date")]
		public System.Nullable<System.DateTime> datFechaAlta
		{
			get
			{
				return this._datFechaAlta;
			}
			set
			{
				if ((this._datFechaAlta != value))
				{
					this._datFechaAlta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitActivo", DbType="Bit")]
		public System.Nullable<bool> bitActivo
		{
			get
			{
				return this._bitActivo;
			}
			set
			{
				if ((this._bitActivo != value))
				{
					this._bitActivo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
