<?xml version="1.0" encoding="utf-8"?><Database Name="dbTyrsa" Class="VigasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=local;Initial Catalog=dbTyrsa;Persist Security Info=True;User ID=usrCotyrsa" SettingsObjectName="Adsisplus.Cotyrsa.DataAccess.Properties.Settings" SettingsPropertyName="dbTyrsaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="" Member="entSeleccionViga">
    <Type Name="entSeleccionViga" Id="ID1">
      <Column Name="SKU" Storage="_vchSKU" Type="System.Int32" CanBeNull="false" />
      <Column Name="sintTipoVigaID" Type="System.Int16" CanBeNull="false" />
      <Column Name="decPesoViga" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decTotal" Member="TOTAL" Storage="_decTotal" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" CanBeNull="false" />
      <Column Name="vchFamiliaViga" Storage="_cvhFamiliaViga" Type="System.String" CanBeNull="false" />
      <Column Name="vchTipo" Type="System.String" CanBeNull="false" />
      <Column Name="vchMaterial" Type="System.String" CanBeNull="false" />
      <Column Name="vchLongitud" Type="System.String" CanBeNull="false" />
      <Column Name="intLargo" Type="System.Int32" CanBeNull="false" />
      <Column Name="intPatin" Type="System.Int32" CanBeNull="false" />
      <Column Name="intPeralte" Type="System.String" CanBeNull="false" />
      <Column Name="decPesoPieza" Type="System.Decimal" CanBeNull="false" />
      <Column Name="decPesoPartida" Type="System.Decimal" CanBeNull="false" />
      <Column Name="sintLongitudId" Type="System.Int16" CanBeNull="false" />
      <Column Name="intTipoID" Type="System.Int32" CanBeNull="false" />
      <Column Name="intMaterialID" Type="System.Int32" CanBeNull="false" />
      <Column Name="bitMontaCarga" Type="System.Boolean" CanBeNull="false" />
      <Column Name="vchDimensionMontacarga" Type="System.String" CanBeNull="false" />
      <Column Member="bitManual" Type="System.Boolean" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.stp_ListarTotalViga" Method="stp_ListarTotalViga">
    <Parameter Name="intTotalViga" Type="System.Int32" DbType="Int" />
    <Parameter Name="intConfiguraVigaID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarTotalVigaResult">
      <Column Name="intTotalViga" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="decTotalConfViga" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="vchInsumoViga" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="decTotalViga" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarConfiguracionViga" Method="stp_ListarConfiguracionViga">
    <Parameter Name="intConfiguraVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintTipoVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCalibreID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCapacidadVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intFactorVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintInsumoViga" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="stp_ListarConfiguracionVigaResult">
      <Column Name="intConfiguraVigaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchTipoViga" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="vchCalibre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="decCapacidadViga" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="vchFactorViga" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="vchInsumoViga" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="decDesarrollo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intLongitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="decAncho" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decLargo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intPiezaxLamina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decPesoPieza" Type="System.Decimal" DbType="Decimal(12,6)" CanBeNull="true" />
      <Column Name="decPesoPartida" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decTotal" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAreaPintura" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intCara" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setConfiguracionViga" Method="stp_setConfiguracionViga">
    <Parameter Name="decFactorAcero" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decFactorRemache" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="decFactorKgMt" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="intNumeroViga" Type="System.Int32" DbType="Int" />
    <Parameter Name="intNumeroPza" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_setConfiguracionVigaResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(55) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarConector_Viga" Method="stp_ListarConector_Viga">
    <Parameter Name="intCalibreID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintInsumoViga" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="sintTipoConectorID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="sintFamiliaVigaID" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="stp_ListarConector_VigaResult">
      <Column Name="intConectorVigaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intCalibreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchCalibre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sintInsumoViga" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchInsumoViga" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="sintTipoConectorID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchTipoConector" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="sintFamiliaVigaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchFamiliaViga" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="decFactorAcero" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decFactorRemache" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="intNumeroConector" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intNumeroPza" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decDesarrollo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intLongitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="decAncho" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decLargo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intPiezaxLamina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intNumPiezaProm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decPesoPieza" Type="System.Decimal" DbType="Decimal(12,6)" CanBeNull="true" />
      <Column Name="decPesoPartida" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decTotal" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAreaPintura" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intCara" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setFactorViga" Method="stp_setFactorViga">
    <Parameter Name="intCalibreID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decAcero" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decRemache" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decKgMetroCuadrado" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decFactorVenta" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decFactorDespiste" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="decFactorDescuento" Type="System.Decimal" DbType="Decimal(12,2)" />
    <ElementType Name="stp_setFactorVigaResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(55) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarConfiguracion_Viga" Method="stp_ListarConfiguracion_Viga">
    <Parameter Name="sintTipoVigaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCalibreID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintFactorVigaID" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="stp_ListarConfiguracion_VigaResult">
      <Column Name="intConfiguraVigaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sintTipoVigaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchTipoViga" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intCalibreID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchCalibre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sintFactorVigaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchAcero" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="decAcero" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="vchRemache" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="decRemache" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="vchKgMetroCuadrado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="decKgMetroCuadrado" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="decFactorAcero" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decFactorRemache" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="decFactorKgMt" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="sintInsumoViga" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intNumeroViga" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intNumeroPza" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decDesarrollo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intLongitud" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="decAncho" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decLargo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intPiezaxLamina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intNumPiezaProm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decPesoPieza" Type="System.Decimal" DbType="Decimal(12,6)" CanBeNull="true" />
      <Column Name="decPesoPartida" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decTotal" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAreaPintura" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intCara" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosViga" Method="stp_ListarDatosViga">
    <Parameter Name="intDatosVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="intElementoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDatoMarcoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosVigaResult">
      <Column Name="intDatosVigaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchPintura" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intElementoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intDatoMarcoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SKU" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sintCantidadDatosMarco" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="decLargo" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="intCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosSeleccionViga" Method="stp_ListarDatosSeleccionViga">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosSeleccionVigaResult">
      <Column Name="intSeleccionVigaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SKU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="decPesoViga" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="intTipoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchTipo" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intMaterialID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vchMaterial" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="decPatin" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decPeralte" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decLongitud" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decCapViga" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decCapVigaMax" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarSeleccionViga" Method="stp_ListarSeleccionViga">
    <Parameter Name="CPPV" Parameter="cPPV" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="LV" Parameter="lV" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="Sistema" Parameter="sistema" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="bitEstructural" Type="System.Boolean" DbType="Bit" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.stp_ListarDatosVigaTope" Method="stp_ListarDatosVigaTope">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosVigaTopeResult">
      <Column Name="intVigaTopeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vchElemento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="intDatosVigaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCantidadDatosViga" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vchPintura" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="vchFolio" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="intCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="bitActivo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_setSeleccionViga" Method="stp_setSeleccionViga">
    <Parameter Name="intRackID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intSeleccionVigaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intCotizacinID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intDetCotizaID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decFrente" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decFondo" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPeso" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decLongitudViga" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decCapCargaReqViga" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="bitEstructural" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="bitSobresale" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcionViga" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="decDistanciaLargoProducto" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="SKU" Parameter="sKU" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="decPesoViga" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPrecioUnitario" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="intTipoID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intMaterialID" Type="System.Int32" DbType="Int" />
    <Parameter Name="decPatin" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decPeralte" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decLongitud" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decCapViga" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="decCapVigaMax" Type="System.Decimal" DbType="Decimal(8,3)" />
    <Parameter Name="intNumeroTarimaPorNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="bitMontaCarga" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="bitManual" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="vchDimensionMontaCarga" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="bitActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="tinOpcion" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="stp_setSeleccionVigaResult">
      <Column Name="vchResultado" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="vchDescripcion" Type="System.String" DbType="VarChar(58) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.stp_ListarDatosPantallaViga" Method="stp_ListarDatosPantallaViga">
    <Parameter Name="intCotizacionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="intSeleccionVigaID" Type="System.Int32" DbType="Int" />
    <ElementType Name="stp_ListarDatosPantallaVigaResult">
      <Column Name="intRackID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="intDetCotizaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCotizacionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intSeleccionVigaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitEstructural" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bitSobresale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="decDistanciaLargoProducto" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decFrente" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decFondo" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decAltura" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decPeso" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="tinOpcionViga" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="decLongitudViga" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="decCapCargaReqViga" Type="System.Decimal" DbType="Decimal(8,3)" CanBeNull="true" />
      <Column Name="sintPinturaID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="intCantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intNumTarimaNivel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bitManual" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bitMontaCarga" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="vchDimensionMontacarga" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>